//! The committed CLI reference chapter of the docs book must be the binary's
//! current help text.
//!
//! `docs/src/cli/reference.md` is generated by `scripts/gen-cli-docs.sh` and
//! committed so the book builds from a bare checkout. This test renders the
//! same chapter from the freshly built binary and compares, so a changed flag
//! or help string fails here until the chapter is regenerated. Hermetic: it
//! needs only the binary cargo built for this test.

use std::path::Path;
use std::process::Command;

/// The subcommands the chapter documents, in the script's order. `help` is
/// clap's own and has no page.
const COMMANDS: [&str; 3] = ["integrate", "generate", "check-events"];

fn help(args: &[&str]) -> String {
    let output = Command::new(env!("CARGO_BIN_EXE_vibegraph"))
        .args(args)
        .arg("--help")
        .output()
        .expect("run vibegraph --help");
    assert!(
        output.status.success(),
        "`vibegraph {} --help` failed: {}",
        args.join(" "),
        String::from_utf8_lossy(&output.stderr)
    );
    String::from_utf8(output.stdout).expect("help text is UTF-8")
}

/// The chapter exactly as `scripts/gen-cli-docs.sh` writes it.
fn render() -> String {
    let mut out = String::new();
    out.push_str(
        "<!-- Generated by scripts/gen-cli-docs.sh from `vibegraph --help`; do not edit. -->\n",
    );
    out.push_str("# Command reference\n\n");
    out.push_str(
        "The text below is what the binary prints for `--help`, for the top-level command\n\
         and for each subcommand. The [command-line overview](overview.md) explains how\n\
         the commands fit together.\n\n",
    );
    out.push_str("## `vibegraph`\n\n```text\n");
    out.push_str(&help(&[]));
    out.push_str("```\n");
    for cmd in COMMANDS {
        out.push_str(&format!("\n## `vibegraph {cmd}`\n\n```text\n"));
        out.push_str(&help(&[cmd]));
        out.push_str("```\n");
    }
    out
}

#[test]
fn committed_cli_reference_matches_the_binary() {
    let path = Path::new(env!("CARGO_MANIFEST_DIR")).join("../docs/src/cli/reference.md");
    let committed =
        std::fs::read_to_string(&path).unwrap_or_else(|e| panic!("read {}: {e}", path.display()));
    let expected = render();
    assert!(
        committed == expected,
        "{} is stale: regenerate it with scripts/gen-cli-docs.sh",
        path.display()
    );
}
