[package]
name = "vibegraph-lib"
version.workspace = true
edition.workspace = true

[lib]
name = "vibegraph"
path = "src/lib.rs"

[features]
extended-validation = []

[dependencies]
num-traits = "0.2"
rand = "0.9"
feyngraph = { git = "https://github.com/Jens-Braun/FeynGraph", branch = "main", default-features = false }
indexmap = "2.14.0"
log = "0.4.29"
num-complex = "0.4.6"
num-rational = "0.4"
peg = "0.8.6"
rustpython-parser = "0.3"
thiserror = "2.0.18"
itertools = "0.14.0"

[dev-dependencies]
libm = "0.2"
