//! Integration test: compare Rust HELAS amplitudes against the Fortran77
//! reference data generated by `validation/helas/gen_reference.py`.
//!
//! This test is gated behind the `extended-validation` cargo feature so it
//! does not run during normal `cargo test`.  The reference data must be
//! generated first with the `helas-validation` pixi environment.
//!
//! Full pipeline:
//!
//!     pixi run -e helas-validation validate-helas
//!
//! Or step by step:
//!
//!     pixi run -e helas-validation build-helas
//!     pixi run -e helas-validation gen-reference
//!     cargo test --features extended-validation --test helas_validation

#[cfg(feature = "extended-validation")]
mod extended {
    use std::path::Path;
    use vibegraph::helas::compute_m2_ee_mumu;

    /// Relative tolerance for comparing Rust |M|² against Fortran reference.
    const REL_TOL: f64 = 1e-6;

    /// Parse the CSV reference file and return rows as (sqrt_s, cos_theta, M2).
    fn read_reference_csv(path: &Path) -> Vec<(f64, f64, f64)> {
        let content = std::fs::read_to_string(path)
            .unwrap_or_else(|e| panic!("Cannot read {}: {}", path.display(), e));

        content
            .lines()
            .skip(1) // header: sqrt_s_GeV,cos_theta,M2_summed
            .filter(|l| !l.trim().is_empty())
            .map(|line| {
                let cols: Vec<&str> = line.split(',').collect();
                assert_eq!(cols.len(), 3, "Expected 3 columns in: {line}");
                let sqrt_s: f64 = cols[0].trim().parse().expect("bad sqrt_s");
                let cos_theta: f64 = cols[1].trim().parse().expect("bad cos_theta");
                let m2: f64 = cols[2].trim().parse().expect("bad M2");
                (sqrt_s, cos_theta, m2)
            })
            .collect()
    }

    #[test]
    fn helas_matches_fortran_reference() {
        let csv_path = Path::new(env!("CARGO_MANIFEST_DIR"))
            .join("validation/helas/reference.csv");

        assert!(
            csv_path.exists(),
            "Reference file not found: {}\n\
             Generate it first with:\n\
             \tpixi run -e helas-validation build-helas\n\
             \tpixi run -e helas-validation gen-reference",
            csv_path.display()
        );

        let rows = read_reference_csv(&csv_path);
        assert!(!rows.is_empty(), "reference.csv is empty");

        let mut failures = 0usize;
        for (sqrt_s, cos_theta, m2_ref) in &rows {
            let m2_rust = compute_m2_ee_mumu(*sqrt_s, *cos_theta);
            let rel_diff = if *m2_ref != 0.0 {
                (m2_rust - m2_ref).abs() / m2_ref.abs()
            } else {
                m2_rust.abs()
            };

            if rel_diff > REL_TOL {
                eprintln!(
                    "FAIL  sqrt_s={sqrt_s:.3} cos_θ={cos_theta:.3}: \
                     Rust={m2_rust:.8e}  Fortran={m2_ref:.8e}  rel_diff={rel_diff:.2e}"
                );
                failures += 1;
            }
        }

        assert_eq!(
            failures, 0,
            "{failures}/{} points exceeded relative tolerance {REL_TOL:.0e}",
            rows.len()
        );
    }
}
