//! Integration test: compare Rust HELAS amplitudes against the Fortran77
//! reference data generated by `validation/helas/gen_reference.py`.
//!
//! This test is gated behind the `extended-validation` cargo feature so it
//! does not run during normal `cargo test`.  The reference data must be
//! generated first with the `helas-validation` pixi environment.
//!
//! Full pipeline:
//!
//!     pixi run -e helas-validation validate-helas
//!
//! Or step by step:
//!
//!     pixi run -e helas-validation build-helas
//!     pixi run -e helas-validation gen-reference
//!     cargo test --features extended-validation --test helas_validation

mod common;

// SM parameters matching MadGraph's default param_card.dat:
//   aEWM1 = 132.507, Gf = 1.16639e-5, MZ = 91.188 GeV, WZ = 2.441404 GeV
const ALPHA_QED_MZ: f64 = 1.0 / 132.507;
const MDL_MZ: f64 = 91.188;
const MDL_WZ: f64 = 2.441_404;
const MDL_ME: f64 = 0.000_511;
const MDL_MMU: f64 = 0.105_658;

fn derive_gammaz_couplings() -> ([f64; 2], [f64; 2]) {
    let aew = ALPHA_QED_MZ;
    let gf = 1.166_39e-5_f64;
    let ee = (4.0 * std::f64::consts::PI * aew).sqrt();
    let sw2 = 0.5
        - (0.25 - std::f64::consts::PI * aew / (gf * std::f64::consts::SQRT_2 * MDL_MZ * MDL_MZ))
            .sqrt();
    let sw = sw2.sqrt();
    let cw = (1.0 - sw2).sqrt();
    let gc_gamma = [-ee, -ee];
    let gl_z = ee * (-0.5 + sw2) / (sw * cw);
    let gr_z = ee * sw / cw;
    ([gc_gamma[0], gc_gamma[1]], [gl_z, gr_z])
}

fn compute_m2_ee_mumu(sqrt_s: f64, cos_theta: f64) -> f64 {
    use itertools::iproduct;
    use vibegraph::helas::{iovxxx, jioxxx};
    use vibegraph::helas::{Charge, InDiracWf, LorentzVector, OutDiracWf, SpinorHelicity};
    use SpinorHelicity::{Down, Up};

    let e_beam = sqrt_s / 2.0;
    let sin_theta = (1.0 - cos_theta * cos_theta).max(0.0).sqrt();
    let (gc_gamma, gc_z) = derive_gammaz_couplings();
    let p3_e = (e_beam * e_beam - MDL_ME * MDL_ME).max(0.0).sqrt();
    let p3_mu = (e_beam * e_beam - MDL_MMU * MDL_MMU).max(0.0).sqrt();
    let p_ep = LorentzVector::new(e_beam, 0.0, 0.0, -p3_e);
    let p_em = LorentzVector::new(e_beam, 0.0, 0.0, p3_e);
    let p_mp = LorentzVector::new(e_beam, -p3_mu * sin_theta, 0.0, -p3_mu * cos_theta);
    let p_mm = LorentzVector::new(e_beam, p3_mu * sin_theta, 0.0, p3_mu * cos_theta);

    let mut sum = 0.0;
    for (nhel_em, nhel_ep) in iproduct!([Down, Up], [Down, Up]) {
        let fi_em = InDiracWf::new(p_em, MDL_ME, nhel_em, Charge::Particle);
        let fo_ep = OutDiracWf::new(p_ep, MDL_ME, nhel_ep, Charge::Antiparticle);
        let v_gamma = jioxxx(&fo_ep, &fi_em, gc_gamma, 0.0, 0.0);
        let v_z = jioxxx(&fo_ep, &fi_em, gc_z, MDL_MZ, MDL_WZ);
        for (nhel_mm, nhel_mp) in iproduct!([Down, Up], [Down, Up]) {
            let fo_mm = OutDiracWf::new(p_mm, MDL_MMU, nhel_mm, Charge::Particle);
            let fi_mp = InDiracWf::new(p_mp, MDL_MMU, nhel_mp, Charge::Antiparticle);
            let amp_gamma = iovxxx(&fo_mm, &fi_mp, &v_gamma, gc_gamma);
            let amp_z = iovxxx(&fo_mm, &fi_mp, &v_z, gc_z);
            sum += (amp_gamma + amp_z).norm_sqr();
        }
    }
    sum
}

#[cfg(test)]
mod eval_vs_hardcoded {
    use super::common::{generate, sm_model};
    use super::{compute_m2_ee_mumu, derive_gammaz_couplings, MDL_MZ};
    use itertools::iproduct;
    use vibegraph::helas::eval::AmplitudeEvaluator;
    use vibegraph::helas::LorentzVector;
    use vibegraph::ufo::slha::ParamCard;

    /// Compare the runtime `AmplitudeEvaluator` against the hardcoded `compute_m2_ee_mumu`
    /// reference for e⁺e⁻→μ⁺μ⁻ at multiple angles and CM energies.
    #[test]
    fn test_eval_m2_ee_mumu_vs_hardcoded() {
        let sets = generate("e+ e- > mu+ mu-");
        assert!(!sets.is_empty(), "no diagram sets generated for e⁺e⁻→μ⁺μ⁻");

        let set = &sets[0];
        assert!(set.diagrams.len() == 2, "expected 2 diagrams (photon+Z)");

        let model = sm_model();
        let empty_card = ParamCard::from_str("").unwrap();
        let evaluated = model.evaluate(&empty_card);

        let evaluator =
            AmplitudeEvaluator::compile(set, model).expect("failed to compile amplitude evaluator");
        assert_eq!(
            evaluator.helicities().len(),
            16,
            "expected 16 helicity combinations"
        );
        assert_eq!(evaluator.n_ext(), 4, "expected 4 external legs");
        assert_eq!(evaluator.n_in(), 2, "expected 2 incoming legs");
        assert_eq!(
            evaluator.n_diagrams(),
            set.diagrams.len(),
            "AST count mismatch"
        );

        // UFO couplings are pure imaginary; the factor of i appears twice per diagram
        // so amplitudes agree up to sign (hence MadGraph's JAMP = -AMP(γ) - AMP(Z)).
        let (gc_gamma, gc_z) = derive_gammaz_couplings();
        let gc_3 = evaluated.coupling(model.coupling_id("GC_3").unwrap());
        assert!(
            (gc_gamma[0] - gc_3.im).abs() < 1e-6,
            "photon coupling mismatch vs GC_3"
        );
        assert!(gc_3.re.abs() < 1e-6, "GC_3 has unexpected real part");
        let gc_59 = evaluated.coupling(model.coupling_id("GC_59").unwrap());
        let gc_50 = evaluated.coupling(model.coupling_id("GC_50").unwrap());
        assert!(
            (gc_z[0] - (gc_59.im + gc_50.im)).abs() < 1e-6,
            "Z left coupling mismatch"
        );
        assert!(
            (gc_z[1] - 2.0 * gc_59.im).abs() < 1e-6,
            "Z right coupling mismatch"
        );

        let me = evaluated.mass(model.particle_id("e-").unwrap());
        let mmu = evaluated.mass(model.particle_id("mu-").unwrap());

        let test_angles = [-0.9_f64, -0.3, 0.0, 0.3, 0.9];
        let test_roots = [1.0_f64, MDL_MZ, 200.0];

        for (cos_theta, sqrt_s) in iproduct!(test_angles, test_roots) {
            let e_beam = sqrt_s / 2.0;
            let sin_theta = (1.0 - cos_theta * cos_theta).max(0.0).sqrt();
            let p3_e = (e_beam * e_beam - me * me).max(0.0).sqrt();
            let p3_mu = (e_beam * e_beam - mmu * mmu).max(0.0).sqrt();
            let momenta = vec![
                LorentzVector::new(e_beam, 0.0, 0.0, -p3_e),
                LorentzVector::new(e_beam, 0.0, 0.0, p3_e),
                LorentzVector::new(e_beam, -p3_mu * sin_theta, 0.0, -p3_mu * cos_theta),
                LorentzVector::new(e_beam, p3_mu * sin_theta, 0.0, p3_mu * cos_theta),
            ];

            let m2_runtime = evaluator.eval_m2(&momenta, &evaluated);
            let m2_hardcoded = compute_m2_ee_mumu(sqrt_s, cos_theta);

            let rel_diff = (m2_runtime - m2_hardcoded).abs() / m2_hardcoded.max(1e-10);
            assert!(
                rel_diff < 1e-4,
                "Mismatch at √s={:.1}, cos_θ={:.1}: runtime={:.4e}, hardcoded={:.4e}, rel_diff={:.2e}",
                sqrt_s, cos_theta, m2_runtime, m2_hardcoded, rel_diff
            );
        }
    }
}

#[cfg(feature = "extended-validation")]
mod extended {
    use super::{compute_m2_ee_mumu, ALPHA_QED_MZ, MDL_MZ};
    use std::f64::consts::PI;
    use std::path::Path;
    use vibegraph::helas::LorentzVector;
    use vibegraph::phasespace::GEV2_TO_PB;

    fn compute_m2_ee_mumu_dynamic(sqrt_s: f64, cos_theta: f64) -> f64 {
        use super::common;
        use vibegraph::helas::eval::AmplitudeEvaluator;
        use vibegraph::ufo::slha::ParamCard;

        let sets = common::generate("e+ e- > mu+ mu-");
        let set = &sets[0];
        let model = common::sm_model();
        let empty_card = ParamCard::from_str("").unwrap();
        let evaluated = model.evaluate(&empty_card);

        let me = evaluated.mass(model.particle_id("e-").unwrap());
        let mmu = evaluated.mass(model.particle_id("mu-").unwrap());

        let evaluator =
            AmplitudeEvaluator::compile(set, model).expect("failed to compile amplitude evaluator");

        let e_beam = sqrt_s / 2.0;
        let sin_theta = (1.0 - cos_theta * cos_theta).max(0.0).sqrt();
        let p3_e = (e_beam * e_beam - me * me).max(0.0).sqrt();
        let p3_mu = (e_beam * e_beam - mmu * mmu).max(0.0).sqrt();
        let momenta = vec![
            LorentzVector::new(e_beam, 0.0, 0.0, -p3_e),
            LorentzVector::new(e_beam, 0.0, 0.0, p3_e),
            LorentzVector::new(e_beam, -p3_mu * sin_theta, 0.0, -p3_mu * cos_theta),
            LorentzVector::new(e_beam, p3_mu * sin_theta, 0.0, p3_mu * cos_theta),
        ];
        evaluator.eval_m2(&momenta, &evaluated)
    }

    /// Relative tolerance for comparing Rust |M|² against Fortran reference.
    const REL_TOL: f64 = 1e-6;

    /// Parse the CSV reference file and return rows as (sqrt_s, cos_theta, M2).
    fn read_reference_csv(path: &Path) -> Vec<(f64, f64, f64)> {
        let content = std::fs::read_to_string(path)
            .unwrap_or_else(|e| panic!("Cannot read {}: {}", path.display(), e));

        content
            .lines()
            .skip(1) // header: sqrt_s_GeV,cos_theta,M2_summed
            .filter(|l| !l.trim().is_empty())
            .map(|line| {
                let cols: Vec<&str> = line.split(',').collect();
                assert_eq!(cols.len(), 3, "Expected 3 columns in: {line}");
                let sqrt_s: f64 = cols[0].trim().parse().expect("bad sqrt_s");
                let cos_theta: f64 = cols[1].trim().parse().expect("bad cos_theta");
                let m2: f64 = cols[2].trim().parse().expect("bad M2");
                (sqrt_s, cos_theta, m2)
            })
            .collect()
    }

    #[test]
    fn helas_matches_fortran_reference() {
        let csv_path =
            Path::new(env!("CARGO_MANIFEST_DIR")).join("../validation/helas/reference.csv");

        assert!(
            csv_path.exists(),
            "Reference file not found: {}\n\
             Generate it first with:\n\
             \tpixi run -e helas-validation build-helas\n\
             \tpixi run -e helas-validation gen-reference",
            csv_path.display()
        );

        let rows = read_reference_csv(&csv_path);
        assert!(!rows.is_empty(), "reference.csv is empty");

        let mut failures = 0usize;
        for (sqrt_s, cos_theta, m2_ref) in &rows {
            let m2_rust = compute_m2_ee_mumu_dynamic(*sqrt_s, *cos_theta);
            let rel_diff = if *m2_ref != 0.0 {
                (m2_rust - m2_ref).abs() / m2_ref.abs()
            } else {
                m2_rust.abs()
            };

            if rel_diff > REL_TOL {
                eprintln!(
                    "FAIL  sqrt_s={sqrt_s:.3} cos_θ={cos_theta:.3}: \
                     Rust={m2_rust:.8e}  Fortran={m2_ref:.8e}  rel_diff={rel_diff:.2e}"
                );
                failures += 1;
            }
        }

        assert_eq!(
            failures,
            0,
            "{failures}/{} points exceeded relative tolerance {REL_TOL:.0e}",
            rows.len()
        );
    }

    /// Compute the total cross section σ(e⁺e⁻ → μ⁺μ⁻) at CM energy √s using VEGAS.
    ///
    /// Integrates the differential cross section over `cosθ ∈ [cos_min, cos_max]`
    /// with a 1D VEGAS adaptive Monte Carlo integrator.  The formula is
    ///
    /// \`\`\`text
    /// σ = prefactor2(√s) × (cos_max − cos_min)/2 × ∫₀¹ Σ|M|²(cosθ(u)) du
    /// \`\`\`
    ///
    /// where [`phasespace::prefactor2`] encodes the flux factor `1/(2s)`, the
    /// spin-averaging factor `1/4`, and the massless 2-body LIPS Jacobian `1/(8π)`.
    /// The `(cos_max − cos_min)/2` factor accounts for integrating over a sub-range
    /// of the full `[−1, 1]` interval.
    ///
    /// # Arguments
    /// * `sqrt_s`    — CM energy √s in GeV
    /// * `cos_range` — `(cos_min, cos_max)` integration range for cosθ; use `(-1.0, 1.0)` for full phase space
    /// * `neval`     — integrand evaluations per VEGAS iteration (typical: 10 000 – 100 000)
    /// * `niter`     — number of VEGAS adaptation iterations (typical: 5 – 10)
    ///
    /// # Returns
    /// `(sigma_GeV2, sigma_err_GeV2)` — cross section and its MC uncertainty in GeV⁻².
    /// Multiply by [`phasespace::GEV2_TO_PB`] to convert to picobarns.
    pub fn sigma_ee_mumu(
        sqrt_s: f64,
        cos_range: (f64, f64),
        neval: usize,
        niter: usize,
    ) -> (f64, f64) {
        use rand::SeedableRng;
        use vibegraph::phasespace;
        use vibegraph::vegas::Vegas;

        let (cos_min, cos_max) = cos_range;
        let prefactor = phasespace::prefactor2(sqrt_s) * (cos_max - cos_min) / 2.0;

        let mut rng = rand::rngs::StdRng::seed_from_u64(42);
        let mut vegas = Vegas::new(1, 50, 1.5);

        // Map u ∈ [0,1] → cosθ ∈ [cos_min, cos_max]
        let result = vegas.integrate(
            |u| {
                let cos_theta = cos_min + u[0] * (cos_max - cos_min);
                compute_m2_ee_mumu(sqrt_s, cos_theta)
            },
            neval,
            niter,
            &mut rng,
        );

        (result.integral * prefactor, result.std_dev * prefactor)
    }

    /// Validate `compute_m2_ee_mumu` and `sigma_ee_mumu` under QED limit.
    /// We use α at MZ scale (as in `compute_m2_ee_mumu`) and allow 3% tolerance
    /// to cover both the MC statistical error and the small off-shell Z
    /// interference term.
    #[test]
    fn sigma_ee_mumu_qed_limit() {
        let sqrt_s = 10.0_f64; // GeV — well below Z pole
        let s = sqrt_s * sqrt_s;

        // Analytic QED prediction using the same α as compute_m2_ee_mumu.
        let alpha = ALPHA_QED_MZ;
        let sigma_analytic = 4.0 * PI * alpha * alpha / (3.0 * s); // GeV⁻²

        let (sigma, err) = sigma_ee_mumu(sqrt_s, (-1.0, 1.0), 50_000, 10);
        let sigma_pb = sigma * GEV2_TO_PB;
        let analytic_pb = sigma_analytic * GEV2_TO_PB;

        let rel = (sigma - sigma_analytic).abs() / sigma_analytic;
        assert!(
            rel < 0.03,
            "σ(e+e-→μ+μ-) at √s={sqrt_s} GeV: \
             MC = {sigma_pb:.4} pb ± {:.4} pb, \
             QED = {analytic_pb:.4} pb, \
             rel_diff = {rel:.4}",
            err * GEV2_TO_PB
        );
    }

    /// Compare the Z-pole cross section directly against MadGraph's result.
    ///
    /// MadGraph5_aMC@NLO (SM, tree-level, ebeam1 = ebeam2 = 45.6 GeV) gives
    /// σ ≈ 2025 pb for e⁺e⁻ → μ⁺μ⁻ at √s = 91.2 GeV with its **default run_card
    /// cuts**: `ptl > 10 GeV` and `etal < 2.5`.
    ///
    /// We apply the same acceptance cuts.  In the massless limit:
    ///
    /// - `ptl > ptl_cut` ↔ `|cosθ| < √(1 − (2·ptl_cut/√s)²)`
    /// - `|η| < etal_cut` ↔ `|cosθ| < tanh(etal_cut)`
    ///
    /// The ptl cut is tighter at the Z pole (cos_max ≈ 0.976 vs 0.987 for η),
    /// so it drives the acceptance.  Muon mass effects are negligible at 91 GeV
    /// (m_μ²/s ≈ 1.3×10⁻⁵).
    ///
    /// Reference: validation/helas/gen_reference.py (σ ≈ 2025 pb at √s = 91.2 GeV).
    #[test]
    fn sigma_ee_mumu_z_pole() {
        const MG5_SIGMA_PB: f64 = 2025.0; // MadGraph5 reference, pb
        const PTL_CUT: f64 = 10.0; // MadGraph default ptl cut, GeV
        const ETAL_CUT: f64 = 2.5; // MadGraph default etal cut

        let sqrt_s = MDL_MZ;
        let p_cm = sqrt_s / 2.0;

        // Acceptance in cosθ from ptl and etal cuts (take the tighter of the two)
        let cos_max_ptl = (1.0 - (PTL_CUT / p_cm).powi(2)).sqrt();
        let cos_max_eta = ETAL_CUT.tanh();
        let cos_max = cos_max_ptl.min(cos_max_eta);

        let (sigma_sm, _err) = sigma_ee_mumu(sqrt_s, (-cos_max, cos_max), 100_000, 10);
        let sigma_sm_pb = sigma_sm * GEV2_TO_PB;

        let rel = (sigma_sm_pb - MG5_SIGMA_PB).abs() / MG5_SIGMA_PB;
        assert!(
            rel < 1e-3,
            "Z-pole σ (with MG5 cuts): our result = {:.1} pb, MadGraph = {:.1} pb, \
             cos_max = {cos_max:.4}, rel_diff = {rel:.4}",
            sigma_sm_pb,
            MG5_SIGMA_PB
        );
    }
}
