//! Validate `pdf::grid` parsing and interpolation against reference oracles
//! generated by the LHAPDF C++ library (`validation/pdf/gen_oracle.cpp`).
//! LHAPDF is the library MadGraph itself evaluates PDFs through, so it is the
//! reference the cross-section pipeline must match.
//!
//! Two oracle files, two grid shapes:
//!   * `oracle.json` — NNPDF23_lo_as_0130_qed, a single rectangular Q²-subgrid.
//!   * `oracle_multigrid.json` — NNPDF31_lo_as_0130, two Q²-subgrids joined at
//!     one internal seam (Q=4.92 GeV). This is what pins the subgrid walk
//!     (which band a point falls in) and the seam interpolation (the one-sided
//!     Q²-derivative each band takes at a boundary) against real LHAPDF values —
//!     behavior the single-subgrid set cannot reach, and which was otherwise
//!     covered only by synthetic in-crate fixtures.
//!
//! Both oracle files are committed. What keeps this in the banked layer is the
//! other side of the comparison: the fetched PDF sets themselves, which is what
//! `pixi run validate` acquires before it runs.
//!
//!     cargo test -p vibegraph-lib --features extended-validation \
//!                --test validate_pdf_grid
//!
//! Per oracle, two kinds of gate share the file. The parser gate compares the
//! "knot" category, where x·f is read directly out of the raw array on both
//! sides (no interpolation), isolating parser correctness. The interpolation
//! gates feed the off_knot/seam/x_to_one_tail/corner categories through the
//! public `xfx_q2` log-bicubic and require ≤1e-9 relative agreement with
//! LHAPDF's own `LogBicubicInterpolator` — the algorithm MadGraph evaluates
//! PDFs through.
//!
//! A third kind of gate shares the same files and the same reference library. A set
//! tabulates the `αs` it was fitted at alongside its densities, LHAPDF reads
//! those knots with a different interpolator again (`AlphaS_Ipol`, a cubic in
//! `ln Q²`), and `pdlabel = lhapdf` makes that reading MadGraph's coupling. The
//! banked events pin it wherever their scales land; the probes here cover what
//! they cannot reach — the ends of the table and past them.
//!
//! A fourth reads the `extrapolated` block: LHAPDF's own continuation past every
//! boundary of the density grid, dumped at two levels (with and without the
//! set's positivity clamp) so the comparison has no floor in it.
//!
//! Blind spot: an oracle of x·f values cannot see a mislabelled flavor whose
//! grid values happen to coincide, nor a global convention shared by both
//! libraries; and the seam gate confirms the walk lands each probe in a band
//! whose interpolant matches LHAPDF, not that any particular internal data
//! structure was traversed.

use serde::Deserialize;
use std::collections::BTreeMap;
use std::path::{Path, PathBuf};
use vibegraph::pdf::alphas::{GridAlphaS, TABULATED_TYPE};
use vibegraph::pdf::PdfSet;

/// Both sides parse the same ASCII float tokens independently (Rust's
/// `f64::from_str` vs. LHAPDF's C++ reader); this tolerance absorbs any
/// last-bit rounding difference between the two parsers without hiding a
/// real mismatch. In practice the on-knot agreement is exact (both use
/// strtod-family parsing of identical tokens).
const REL_TOL: f64 = 1e-12;

#[derive(Deserialize)]
struct Oracle {
    set: String,
    member: u32,
    #[serde(default)]
    seams: Vec<f64>,
    subgrids: Vec<OracleSubgrid>,
    points: Vec<OraclePoint>,
    /// The set's `AlphaS_Type`. The probes below are `AlphaS_Ipol`'s values, so
    /// a set that derives its coupling some other way would need a different
    /// comparison rather than a looser one.
    #[serde(default)]
    alphas_type: String,
    #[serde(default)]
    alphas: Vec<OracleAlphaPoint>,
    /// The `Extrapolator` LHAPDF resolved for this set. The probes below are
    /// that object's values, so a build whose config named a different one has
    /// to fail here rather than silently redefine the reference.
    #[serde(default)]
    extrapolator: String,
    /// The set's `ForcePositive` level, which is applied on top of every value
    /// LHAPDF hands out but not to the continuation itself.
    #[serde(default)]
    force_positive: i32,
    #[serde(default)]
    extrapolated: Vec<OracleExtrapPoint>,
}

/// One out-of-grid probe, carried at two levels: `xf_raw` is
/// `Extrapolator::extrapolateXQ2` with nothing applied on top, and `xf` is
/// `PDF::xfxQ2` — the same number with the set's positivity clamp. The
/// comparison below is against `xf_raw`, which has no clamp in it to hide a
/// disagreement behind.
#[derive(Deserialize)]
struct OracleExtrapPoint {
    category: String,
    pdg: i32,
    x: f64,
    q2: f64,
    xf: f64,
    xf_raw: f64,
}

#[derive(Deserialize)]
struct OracleAlphaPoint {
    category: String,
    q: f64,
    alphas: f64,
}

#[derive(Deserialize)]
struct OracleSubgrid {
    nx: usize,
    nq: usize,
    flavors: Vec<i32>,
}

#[derive(Deserialize)]
struct OraclePoint {
    category: String,
    pdg: i32,
    x: f64,
    q2: f64,
    xf: f64,
}

fn validation_dir() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("../validation/pdf")
}

/// Both dumps are committed — LHAPDF's values on a fixed set of probe points do
/// not change — so an absent one is a broken checkout, not a missing optional
/// input. Regenerating them needs the LHAPDF C++ build:
/// `pixi run generate-references refs`.
fn load_oracle_named(name: &str) -> Oracle {
    let path = validation_dir().join(name);
    let content = std::fs::read_to_string(&path)
        .unwrap_or_else(|e| panic!("cannot read {}: {e}", path.display()));
    serde_json::from_str(&content)
        .unwrap_or_else(|e| panic!("failed to parse {}: {e}", path.display()))
}

fn load_oracle() -> Oracle {
    load_oracle_named("oracle.json")
}

fn load_multigrid_oracle() -> Oracle {
    load_oracle_named("oracle_multigrid.json")
}

fn load_set(oracle: &Oracle) -> PdfSet {
    let set_dir = validation_dir().join(&oracle.set);
    PdfSet::load(&set_dir, &oracle.set).unwrap_or_else(|e| {
        panic!(
            "failed to load PDF set at {}: {e}\n\
             run `pixi run -e madgraph fetch-pdf` first",
            set_dir.display()
        )
    })
}

/// The member at the level the set's own `.info` resolves — what MadGraph
/// itself reads through LHAPDF.
fn load_member(oracle: &Oracle) -> vibegraph::pdf::PdfMember {
    let set = load_set(oracle);
    set.member(oracle.member).expect("member load")
}

/// The same member with any positivity clamp stripped, for comparisons
/// against `xf_raw` — LHAPDF's continuation before its own clamp runs.
fn load_unclamped_member(oracle: &Oracle) -> vibegraph::pdf::PdfMember {
    load_member(oracle).with_force_positive(0)
}

fn rel_close(a: f64, b: f64) -> bool {
    (a - b).abs() <= REL_TOL * a.abs().max(b.abs()).max(f64::MIN_POSITIVE)
}

#[test]
fn subgrid_structure_matches_oracle() {
    let oracle = load_oracle();
    let set = load_set(&oracle);
    let member = set
        .member(oracle.member)
        .expect("failed to load reference member");

    assert_eq!(
        member.subgrids.len(),
        oracle.subgrids.len(),
        "subgrid count mismatch"
    );
    for (i, (sg, osg)) in member.subgrids.iter().zip(&oracle.subgrids).enumerate() {
        assert_eq!(sg.nx(), osg.nx, "subgrid {i}: x-knot count mismatch");
        assert_eq!(sg.nq(), osg.nq, "subgrid {i}: Q-knot count mismatch");
        assert_eq!(sg.flavors, osg.flavors, "subgrid {i}: flavor list mismatch");
    }
}

#[test]
fn on_knot_values_match_oracle_exactly() {
    let oracle = load_oracle();
    let set = load_set(&oracle);
    let member = set
        .member(oracle.member)
        .expect("failed to load reference member");

    let knot_points: Vec<&OraclePoint> = oracle
        .points
        .iter()
        .filter(|p| p.category == "knot")
        .collect();
    assert!(!knot_points.is_empty(), "oracle has no on-knot points");

    let mut checked = 0usize;
    for p in &knot_points {
        let sg = member
            .subgrids
            .iter()
            .find(|sg| {
                sg.x.iter().any(|&xv| rel_close(xv, p.x))
                    && sg.q2.iter().any(|&qv| rel_close(qv, p.q2))
            })
            .unwrap_or_else(|| panic!("no subgrid contains knot x={} q2={}", p.x, p.q2));

        let ix = sg.x.iter().position(|&xv| rel_close(xv, p.x)).unwrap();
        let iq = sg.q2.iter().position(|&qv| rel_close(qv, p.q2)).unwrap();
        let ifl = sg
            .flavor_index(p.pdg)
            .unwrap_or_else(|| panic!("flavor {} not found in subgrid", p.pdg));

        let got = sg.xf_at(ix, iq, ifl);
        assert!(
            rel_close(got, p.xf),
            "xf mismatch at pdg={} x={} q2={}: rust={got} oracle={}",
            p.pdg,
            p.x,
            p.q2,
            p.xf
        );
        checked += 1;
    }
    eprintln!("checked {checked} on-knot (pdg, x, Q²) points against the LHAPDF oracle");
}

#[test]
fn info_flavors_cover_dat_flavors() {
    let oracle = load_oracle();
    let set = load_set(&oracle);
    for osg in &oracle.subgrids {
        for &f in &osg.flavors {
            assert!(
                set.info.flavors.contains(&f),
                "subgrid flavor {f} not listed in {}.info Flavors",
                oracle.set
            );
        }
    }
}

/// Relative error of the Rust log-bicubic value against the LHAPDF oracle,
/// screened by an absolute floor on the *oracle* value: where LHAPDF's
/// reference is at or below `atol`, the point is treated as agreeing. This
/// keys on `want`, not on both sides, because a positivity-clamped set floors
/// its own output there while vibegraph evaluates the raw log-bicubic, whose
/// un-clamped value can overshoot to a small non-zero of either sign — so
/// the magnitudes need not both be tiny even though the point is negligible.
/// `atol == 0` recovers a pure relative error where only an exact oracle zero
/// (an absent flavor, which vibegraph also returns as zero) is agreement.
fn rel_err(got: f64, want: f64, atol: f64) -> f64 {
    if want.abs() <= atol {
        return 0.0;
    }
    let denom = got.abs().max(want.abs());
    (got - want).abs() / denom
}

/// Worst relative error over all oracle points in `category`, plus the
/// point where it occurs, computed through the public `xfx_q2` API. Points
/// at or below `atol` in magnitude on both sides are treated as agreeing.
fn worst_in_category(
    member: &vibegraph::pdf::PdfMember,
    oracle: &Oracle,
    category: &str,
    atol: f64,
) -> f64 {
    let mut worst = 0.0f64;
    let mut worst_at = None;
    let mut count = 0usize;
    for p in oracle.points.iter().filter(|p| p.category == category) {
        let got: f64 = member.xfx_q2(p.pdg, p.x, p.q2);
        let e = rel_err(got, p.xf, atol);
        if e > worst {
            worst = e;
            worst_at = Some((p, got));
        }
        count += 1;
    }
    assert!(count > 0, "oracle has no '{category}' points");
    if let Some((p, got)) = worst_at {
        eprintln!(
            "category '{category}': {count} points, worst rel {worst:.3e} at \
             pdg={} x={} Q²={} (rust={got:.17e} oracle={:.17e})",
            p.pdg, p.x, p.q2, p.xf
        );
    } else {
        eprintln!("category '{category}': {count} points, worst rel 0 (all exact)");
    }
    worst
}

/// The accept bar: interior (off-knot) interpolation reproduces LHAPDF's
/// log-bicubic to ≤1e-9 relative. Because the Rust scheme replicates
/// LHAPDF's exact per-point arithmetic, the observed agreement is far
/// tighter (~1e-13); the loose bar leaves headroom for platform libm
/// differences in `log`.
#[test]
fn off_knot_interpolation_matches_lhapdf() {
    let oracle = load_oracle();
    let set = load_set(&oracle);
    let member = set.member(oracle.member).expect("member load");
    let worst = worst_in_category(&member, &oracle, "off_knot", 0.0);
    assert!(worst <= 1e-9, "off_knot worst rel {worst:.3e} exceeds 1e-9");
}

/// Grid corners and the x→1 tail exercise the one-sided finite-difference
/// derivative branches (lower/upper Q² edge, last x-interval). Same exact
/// algorithm, so the same ≤1e-9 bar holds. The `corner` category also
/// probes the gluon under both PDG spellings (21 and the 0 alias).
#[test]
fn edge_and_tail_interpolation_matches_lhapdf() {
    let oracle = load_oracle();
    let set = load_set(&oracle);
    let member = set.member(oracle.member).expect("member load");
    for category in ["seam", "x_to_one_tail", "corner"] {
        let worst = worst_in_category(&member, &oracle, category, 0.0);
        assert!(
            worst <= 1e-9,
            "{category} worst rel {worst:.3e} exceeds 1e-9"
        );
    }
}

/// On-knot points must interpolate back to the tabulated `x·f` value: at a
/// knot the local Hermite reproduces the node (up to libm `log` rounding),
/// a self-consistency the raw-parser gate cannot see since it reads the
/// array directly rather than going through interpolation. The oracle's
/// `knot` category holds the *raw* grid value, so vanishing nodes (e.g.
/// x·f→0 at x=1) need an absolute floor: the Hermite sum of large cancelling
/// coefficients lands at ~1e-20 rather than a bit-exact 0, which is a pure
/// relative error of 1 against a zero node but a negligible absolute one.
/// Bar: `|Δ| ≤ 1e-11 + 1e-9·|want|` (numpy-style atol+rtol).
#[test]
fn on_knot_interpolation_reproduces_node() {
    let oracle = load_oracle();
    let set = load_set(&oracle);
    let member = set.member(oracle.member).expect("member load");
    let mut worst_abs = 0.0f64;
    let mut count = 0usize;
    for p in oracle.points.iter().filter(|p| p.category == "knot") {
        let got: f64 = member.xfx_q2(p.pdg, p.x, p.q2);
        let delta = (got - p.xf).abs();
        let bound = 1e-11 + 1e-9 * p.xf.abs();
        assert!(
            delta <= bound,
            "on-knot interpolation off at pdg={} x={} Q²={}: rust={got:.17e} \
             oracle={:.17e} |Δ|={delta:.3e} > {bound:.3e}",
            p.pdg,
            p.x,
            p.q2,
            p.xf
        );
        worst_abs = worst_abs.max(delta);
        count += 1;
    }
    eprintln!("on-knot interpolation: {count} points, worst |Δ| {worst_abs:.3e}");
}

/// Which points still have no reading, now that the ones past the grid do.
///
/// Blind spot: this pins the *policy* at each of these points, not a value —
/// the values past the grid are pinned against LHAPDF further down.
#[test]
fn only_the_points_lhapdf_has_no_reading_for_are_refused() {
    let oracle = load_oracle();
    let set = load_set(&oracle);
    let member = set.member(oracle.member).expect("member load");

    // Below XMin=1e-9 in x, and above QMax in Q²: both continue.
    assert!(member.try_xfx_q2(2, 1e-12, 1e6).is_ok());
    assert!(member.try_xfx_q2(2, 0.1, 1e12).is_ok());
    assert!(member.try_xfx_q2(2, 1e-12, 1e12).is_ok());
    assert!(member.try_xfx_q2(2, 0.1, 0.5).is_ok());

    // Above the last x knot there is nothing to continue into, and a point that
    // is not a point has no reading in any direction.
    assert!(member.try_xfx_q2(2, 2.0, 100.0).is_err());
    assert!(member.try_xfx_q2(2, 0.0, 100.0).is_err());
    assert!(member.try_xfx_q2(2, -0.1, 100.0).is_err());
    assert!(member.try_xfx_q2(2, f64::NAN, 100.0).is_err());
    assert!(member.try_xfx_q2(2, 0.1, -1.0).is_err());
    assert!(member.try_xfx_q2(2, 0.1, f64::NAN).is_err());
    assert!(member.try_xfx_q2(2, 0.1, f64::INFINITY).is_err());
}

// ── Multi-Q²-subgrid coverage (MSHT20lo_as130) ─────────────────────────
//
// A single-subgrid set never exercises the subgrid walk or the one-sided
// Q²-derivative each band takes at an internal seam. These gates pin both
// against real LHAPDF values on a three-band set.

#[test]
fn multigrid_subgrid_structure_matches_oracle() {
    let oracle = load_multigrid_oracle();
    assert!(
        oracle.subgrids.len() >= 2,
        "the multi-subgrid oracle must carry ≥2 Q²-subgrids, got {}",
        oracle.subgrids.len()
    );
    let set = load_set(&oracle);
    let member = set
        .member(oracle.member)
        .expect("failed to load reference member");

    assert_eq!(
        member.subgrids.len(),
        oracle.subgrids.len(),
        "subgrid count mismatch"
    );
    for (i, (sg, osg)) in member.subgrids.iter().zip(&oracle.subgrids).enumerate() {
        assert_eq!(sg.nx(), osg.nx, "subgrid {i}: x-knot count mismatch");
        assert_eq!(sg.nq(), osg.nq, "subgrid {i}: Q-knot count mismatch");
        // Compare flavors as a set, not a sequence: LHAPDF canonicalizes the
        // flavor order (gluon last) in its KnotArray, while the parser keeps
        // the `.dat` file order (gluon mid-list for this set). Both index x·f
        // by PDG code, so the ordering is an internal detail; the invariant
        // that must hold is that the same flavors are present.
        let mut got = sg.flavors.clone();
        let mut want = osg.flavors.clone();
        got.sort_unstable();
        want.sort_unstable();
        assert_eq!(got, want, "subgrid {i}: flavor set mismatch");
    }

    // Each declared seam is the shared upper/lower Q² knot of two adjacent
    // parsed bands.
    assert!(
        !oracle.seams.is_empty(),
        "oracle declares no internal seams"
    );
    for &seam in &oracle.seams {
        let bordering = member
            .subgrids
            .iter()
            .filter(|sg| {
                rel_close(*sg.q2.first().unwrap(), seam) || rel_close(*sg.q2.last().unwrap(), seam)
            })
            .count();
        assert!(
            bordering >= 2,
            "seam Q²={seam} does not border two bands (found {bordering})"
        );
    }
}

#[test]
fn multigrid_on_knot_values_match_oracle_exactly() {
    let oracle = load_multigrid_oracle();
    let set = load_set(&oracle);
    let member = set
        .member(oracle.member)
        .expect("failed to load reference member");

    let mut checked = 0usize;
    for p in oracle.points.iter().filter(|p| p.category == "knot") {
        let sg = member
            .subgrids
            .iter()
            .find(|sg| {
                sg.x.iter().any(|&xv| rel_close(xv, p.x))
                    && sg.q2.iter().any(|&qv| rel_close(qv, p.q2))
            })
            .unwrap_or_else(|| panic!("no subgrid contains knot x={} q2={}", p.x, p.q2));
        let ix = sg.x.iter().position(|&xv| rel_close(xv, p.x)).unwrap();
        let iq = sg.q2.iter().position(|&qv| rel_close(qv, p.q2)).unwrap();
        let ifl = sg
            .flavor_index(p.pdg)
            .unwrap_or_else(|| panic!("flavor {} not in subgrid", p.pdg));
        let got = sg.xf_at(ix, iq, ifl);
        assert!(
            rel_close(got, p.xf),
            "xf mismatch at pdg={} x={} q2={}: rust={got} oracle={}",
            p.pdg,
            p.x,
            p.q2,
            p.xf
        );
        checked += 1;
    }
    eprintln!("multigrid: checked {checked} on-knot points against the LHAPDF oracle");
}

/// This set carries `ForcePositive: 2` in its `.info`, and this crate now
/// applies that clamp too. The screen still earns its keep: this crate's raw
/// log-bicubic and LHAPDF's own interpolated value are computed by
/// independent arithmetic, so on a value close enough to the `1e-10` floor
/// the two could round to opposite sides of it and clamp (or not) differently
/// even though both algorithms agree to their usual precision. `atol` absorbs
/// exactly that straddle band; every physical value (≳1e-4 at these points)
/// is compared at full relative precision regardless. Measured on
/// `oracle_multigrid.json`: the smallest in-range value strictly above the
/// floor is `1.1039e-10` (10.4% above it) and 84 in-range points sit exactly
/// at the floor, so nothing in this probe set is within nine orders of the
/// straddle — `an_in_grid_value_lhapdf_floors_is_floored_here_too` is what
/// pins the floored points exactly rather than through this screen.
const FORCE_POSITIVE_FLOOR: f64 = 1e-8;

#[test]
fn multigrid_off_knot_interpolation_matches_lhapdf() {
    let oracle = load_multigrid_oracle();
    let member = load_member(&oracle);
    let worst = worst_in_category(&member, &oracle, "off_knot", FORCE_POSITIVE_FLOOR);
    assert!(worst <= 1e-9, "off_knot worst rel {worst:.3e} exceeds 1e-9");
}

/// The load-bearing seam gate. Each "seam" oracle point sits either inside
/// the lower band's last Q² interval, inside the upper band's first
/// interval, or exactly on the shared seam knot. Reproducing LHAPDF at all
/// three pins that the subgrid walk selects the band LHAPDF uses *and* that
/// each band takes the same one-sided Q²-derivative LHAPDF's flattened
/// (duplicated-knot) array forces there. Blind spot: agreement here shows
/// the walk lands each probe in a band whose interpolant matches LHAPDF; it
/// does not, on its own, distinguish the exact-seam value's band since the
/// value is continuous across the seam by construction.
#[test]
fn multigrid_seam_interpolation_matches_lhapdf() {
    let oracle = load_multigrid_oracle();
    assert!(
        !oracle.seams.is_empty(),
        "expected ≥1 internal seam, got {}",
        oracle.seams.len()
    );
    let member = load_member(&oracle);
    let worst = worst_in_category(&member, &oracle, "seam", FORCE_POSITIVE_FLOOR);
    assert!(worst <= 1e-9, "seam worst rel {worst:.3e} exceeds 1e-9");
}

/// Crossing an internal seam is a derivative kink, not a value jump: the
/// x·f value is continuous while its Q²-derivative changes as the walk hands
/// off between bands. Probe just below, at, and just above each seam and
/// require the value to move continuously — a gross band mix-up (reading the
/// wrong band's offset) would show up as a step here.
#[test]
fn multigrid_value_is_continuous_across_seams() {
    let oracle = load_multigrid_oracle();
    let member = load_member(&oracle);
    let x = 0.05_f64;
    for &seam in &oracle.seams {
        let below = seam * (1.0 - 1e-7);
        let above = seam * (1.0 + 1e-7);
        let v_below: f64 = member.xfx_q2(2, x, below);
        let v_at: f64 = member.xfx_q2(2, x, seam);
        let v_above: f64 = member.xfx_q2(2, x, above);
        let scale = v_at.abs().max(1e-12);
        assert!(
            (v_at - v_below).abs() <= 1e-4 * scale,
            "value jumps below seam Q²={seam}: {v_below} vs {v_at}"
        );
        assert!(
            (v_above - v_at).abs() <= 1e-4 * scale,
            "value jumps above seam Q²={seam}: {v_at} vs {v_above}"
        );
    }
}

/// How far this crate's `αs` may sit from LHAPDF's on the same probe scale.
///
/// Both sides run `AlphaS_Ipol`'s cubic over the same knots, so the residual is
/// arithmetic noise around a number of order `0.1`: a `ln` per query in the
/// interpolating branch, a `log10` pair and a `powf` in the branch below the
/// table, each good to an ulp or so. The bound sits two orders above that, which
/// is headroom for a system `libm` that rounds those differently and still four
/// orders below the `1.7e-4` a straight-line reading of the same knots would
/// cost mid-interval.
const ALPHA_S_REL_TOL: f64 = 1e-14;

/// `αs(Q)` against LHAPDF's own values, over the whole tabulated range and past
/// both ends of it.
///
/// The banked MadGraph events pin the interpolation event by event
/// (`validate_alphas.rs`), but only where their scales land: every one of the
/// 20 000 sits strictly inside the table, so the two continuations — frozen above
/// the last knot, a log-log straight line below the first — have no event behind
/// them at all. The probe categories below are where that gap is closed, and the
/// `threshold` ones (only the multigrid set has a repeated scale, at `Q = 4.92`)
/// are the only reference for the subgrid split.
///
/// Blind spot: an `αs(Q)` oracle says nothing about *which* scale a process
/// evaluates the coupling at — that is `validate_scales.rs` — and a probe set is
/// a finite sample, so it cannot exclude a disagreement between probes. The event
/// oracle is what covers the interior densely; this covers the shape of the
/// range.
#[test]
fn alpha_s_matches_lhapdf_across_the_table_and_past_both_ends() {
    for name in ["oracle.json", "oracle_multigrid.json"] {
        let oracle = load_oracle_named(name);
        assert_eq!(
            oracle.alphas_type, TABULATED_TYPE,
            "{name}: the oracle was dumped from a set whose alpha_s is not tabulated"
        );
        let set = load_set(&oracle);
        let grid =
            GridAlphaS::from_info(&set.info.alpha_s).unwrap_or_else(|e| panic!("{name}: {e}"));
        assert!(
            !oracle.alphas.is_empty(),
            "{name}: carries no alpha_s probes; regenerate with \
             `pixi run -e madgraph generate-pdf-oracle`"
        );

        let mut by_category: BTreeMap<&str, (usize, f64, f64)> = BTreeMap::new();
        for probe in &oracle.alphas {
            let got = grid.eval(probe.q);
            let rel = (got - probe.alphas).abs() / probe.alphas.abs();
            let entry = by_category
                .entry(probe.category.as_str())
                .or_insert((0, 0.0, 0.0));
            entry.0 += 1;
            // `>=` so the reported scale is a real probe even when every
            // category agrees exactly and there is no strict worst.
            if rel >= entry.1 {
                *entry = (entry.0, rel, probe.q);
            }
        }
        for (category, (n, worst, at)) in &by_category {
            println!("{name} {category}: {n} probes, worst {worst:.2e} at Q = {at}");
            assert!(
                *worst <= ALPHA_S_REL_TOL,
                "{name} {category}: alpha_s misses LHAPDF by {worst:.2e} at Q = {at}"
            );
        }
        // Every branch of the reading has to be exercised, or the gate is a
        // statement about the interior wearing the range's name.
        for required in ["knot", "interval", "above_qmax", "below_qmin"] {
            assert!(
                by_category.contains_key(required),
                "{name}: no {required} probes"
            );
        }
    }
}

/// The frozen continuation above the table, read off LHAPDF's own probes rather
/// than off the source it was derived from.
///
/// This is the branch a 13 TeV collider reaches on a set whose `αs` table stops
/// at 10 TeV, and the whole reason a dynamical scale is evaluable there at all.
/// It is asserted separately from the tolerance sweep above because it is a
/// *shape* claim — one value, however far past the table — and a sweep that
/// happened to agree at three nearby probes would not say that.
#[test]
fn above_the_alpha_s_table_lhapdf_freezes_rather_than_extrapolates() {
    for name in ["oracle.json", "oracle_multigrid.json"] {
        let oracle = load_oracle_named(name);
        let set = load_set(&oracle);
        let last = *set.info.alpha_s.vals.last().expect("tabulated alpha_s");
        let above: Vec<&OracleAlphaPoint> = oracle
            .alphas
            .iter()
            .filter(|p| p.category == "above_qmax")
            .collect();
        assert!(above.len() >= 3, "{name}: too few probes above the table");
        let spread = above
            .iter()
            .map(|p| (p.alphas - last).abs())
            .fold(0.0f64, f64::max);
        assert_eq!(
            spread, 0.0,
            "{name}: LHAPDF's alpha_s above the table is not the last tabulated \
             value {last}"
        );
        let (lo, hi) = (
            above.iter().map(|p| p.q).fold(f64::MAX, f64::min),
            above.iter().map(|p| p.q).fold(0.0f64, f64::max),
        );
        println!(
            "{name}: alpha_s frozen at {last} over Q = {lo} .. {hi} \
             ({} probes)",
            above.len()
        );
    }
}

// ── The out-of-grid continuation ───────────────────────────────────────────
//
// A grid stops where the fit stopped; the physics does not. LHAPDF continues
// past both Q² ends and below the x floor through an `Extrapolator` chosen per
// set, and since MadGraph reads its densities through LHAPDF, that continuation
// is part of the reference a cross section has to match. These gates are its
// only oracle: no banked event is out of grid, by construction — the events that
// survive unweighting sit well inside it, which is exactly why an integration
// reaches past the ceiling where a bank cannot.

/// How far this crate's continued `x·f` may sit from LHAPDF's on the same probe.
///
/// Both sides run the same arithmetic on the same edge readings, so the input to
/// the residual is one ulp of the interpolation — but the continuation itself is
/// ill-conditioned where it is most interesting. A straight line evaluated far
/// *outside* the pair of points that define it is a difference of two much
/// larger numbers, and at a large `x` where `x·f` has all but died the
/// cancellation runs to three orders. The observed residual is therefore not
/// flat: it is one ulp times each point's own condition number, reaching
/// `2.4e-13` on the gluon at `x = 0.7`, four decades above the ceiling.
///
/// This flat bound is the coarse net, an order above that worst case and eight
/// orders below what a branch or knot-pair confusion produces (tens of percent
/// at least). The sharp statement — that the residual *is* one ulp once the
/// conditioning is divided out — is made per point further down.
const EXTRAP_REL_TOL: f64 = 1e-11;

/// One ulp of the interpolated endpoint values, with headroom for a system
/// `libm` that rounds a couple of `log` calls differently. This is the scale the
/// continuation is really held to, once each point's own amplification of that
/// ulp is divided out.
const EXTRAP_CONDITIONED_TOL: f64 = 1e-14;

/// Relative error with no absolute screen: an exact oracle zero demands an exact
/// zero back. The interpolated categories screen sub-floor values because a
/// positivity-clamped set floors its own output there, but these probes compare
/// against the *unclamped* `xf_raw`, so there is nothing to screen and a zero is
/// a real claim (an absent flavor, or a density the power law drove to zero).
fn extrap_rel_err(got: f64, want: f64) -> f64 {
    if want == 0.0 {
        return if got == 0.0 { 0.0 } else { f64::INFINITY };
    }
    (got - want).abs() / got.abs().max(want.abs())
}

/// The continuation against LHAPDF's own `ContinuationExtrapolator`, on probes
/// past every boundary a query can cross.
///
/// Blind spot: a probe set is a finite sample of a continuous surface, so this
/// cannot exclude a disagreement between probes; and an `x·f` oracle says
/// nothing about *which* `(x, Q²)` a process asks for. What it does cover is
/// every branch — each of the four out-of-range quadrants is a named category,
/// and the assertion at the bottom fails if one stops being emitted.
#[test]
fn extrapolation_matches_lhapdf_past_every_grid_boundary() {
    for name in ["oracle.json", "oracle_multigrid.json"] {
        let oracle = load_oracle_named(name);
        assert_eq!(
            oracle.extrapolator, "continuation",
            "{name}: dumped from a set LHAPDF continued some other way"
        );
        let member = load_unclamped_member(&oracle);
        assert!(
            !oracle.extrapolated.is_empty(),
            "{name}: carries no out-of-grid probes; regenerate with \
             `pixi run -e madgraph generate-pdf-oracle`"
        );

        let mut by_category: BTreeMap<&str, (usize, f64, String)> = BTreeMap::new();
        for probe in &oracle.extrapolated {
            let got: f64 = member
                .try_xfx_q2(probe.pdg, probe.x, probe.q2)
                .unwrap_or_else(|e| {
                    panic!(
                        "{name}: LHAPDF continued (pdg={}, x={}, Q²={}) to {} and this \
                         crate refused it: {e}",
                        probe.pdg, probe.x, probe.q2, probe.xf_raw
                    )
                });
            let rel = extrap_rel_err(got, probe.xf_raw);
            let entry =
                by_category
                    .entry(probe.category.as_str())
                    .or_insert((0, 0.0, String::new()));
            entry.0 += 1;
            if rel >= entry.1 {
                *entry = (
                    entry.0,
                    rel,
                    format!(
                        "pdg={} x={} Q²={} (rust={got:.17e} lhapdf={:.17e})",
                        probe.pdg, probe.x, probe.q2, probe.xf_raw
                    ),
                );
            }
        }
        for (category, (n, worst, at)) in &by_category {
            println!("{name} {category}: {n} probes, worst {worst:.2e} at {at}");
            assert!(
                *worst <= EXTRAP_REL_TOL,
                "{name} {category}: the continuation misses LHAPDF by {worst:.2e} at {at}"
            );
        }
        for required in [
            "above_q2max",
            "below_xmin",
            "below_xmin_above_q2max",
            "below_q2min",
            "below_q2min_below_xmin",
        ] {
            assert!(
                by_category.contains_key(required),
                "{name}: no {required} probes"
            );
        }
    }
}

/// Which of the two `_extrapolateLinear` branches LHAPDF took, decided against
/// its own values rather than assumed from reading its source.
///
/// The branch is chosen by the two endpoint values the line runs through, so it
/// is reconstructible: take those two readings off this crate's interpolator at
/// the grid's top two Q² knots, build both candidate continuations, and see
/// which one LHAPDF's number is. Where both endpoints clear `1e-3` it must be
/// the log-linear one and the linear one must be visibly different; where they
/// do not it must be the linear one. Getting this backwards is a silent factor
/// of order one on a density, and no |x·f| comparison at a single point could
/// tell the two apart if the probe set happened to sit on one side of the floor.
#[test]
fn the_branch_of_the_upper_continuation_is_the_one_the_endpoint_values_select() {
    for name in ["oracle.json", "oracle_multigrid.json"] {
        let oracle = load_oracle_named(name);
        let member = load_unclamped_member(&oracle);
        let top = member.subgrids.last().expect("at least one subgrid");
        let q2_max = *top.q2.last().unwrap();
        let q2_max1 = top.q2[top.q2.len() - 2];

        let (mut log_linear, mut linear) = (0usize, 0usize);
        for probe in oracle
            .extrapolated
            .iter()
            .filter(|p| p.category == "above_q2max")
        {
            let y_lo: f64 = member.xfx_q2(probe.pdg, probe.x, q2_max);
            let y_hi: f64 = member.xfx_q2(probe.pdg, probe.x, q2_max1);
            let t = (probe.q2.ln() - q2_max.ln()) / (q2_max1.ln() - q2_max.ln());
            let candidate_linear = y_lo + t * (y_hi - y_lo);
            // A log-linear continuation of a non-positive endpoint is not a
            // number, which is the other half of why the branch exists.
            if !(y_lo > 1e-3 && y_hi > 1e-3) {
                assert!(
                    extrap_rel_err(candidate_linear, probe.xf_raw) <= 1e-9,
                    "{name}: sub-floor endpoints ({y_lo}, {y_hi}) did not take the \
                     linear branch at pdg={} x={} Q²={}",
                    probe.pdg,
                    probe.x,
                    probe.q2
                );
                linear += 1;
                continue;
            }
            let candidate_log = (y_lo.ln() + t * (y_hi.ln() - y_lo.ln())).exp();
            assert!(
                extrap_rel_err(candidate_log, probe.xf_raw) <= 1e-9,
                "{name}: positive endpoints ({y_lo}, {y_hi}) did not take the \
                 log-linear branch at pdg={} x={} Q²={}",
                probe.pdg,
                probe.x,
                probe.q2
            );
            // The negative control: the branch is only pinned where the two
            // candidates actually disagree, so require that and count it.
            if extrap_rel_err(candidate_linear, probe.xf_raw) > 1e-3 {
                log_linear += 1;
            }
        }
        println!(
            "{name}: {log_linear} probes where the log-linear branch is \
             distinguishable from the linear one, {linear} on the linear branch"
        );
        assert!(
            log_linear > 0 && linear > 0,
            "{name}: the probes do not reach both branches ({log_linear}, {linear})"
        );
    }
}

/// The set's positivity clamp is the only thing standing between the
/// continuation and the number MadGraph sees, and this crate now applies it.
///
/// `xf_raw` is `Extrapolator::extrapolateXQ2` and `xf` is `PDF::xfxQ2` on the
/// same point; the difference is `ForcePositive` and nothing else. This pins
/// both sides of that relationship: the oracle-internal one (`xf ==
/// clamp(xf_raw)`, which fixes what LHAPDF itself does) and this crate's own
/// (a clamped member's reading equals `xf` wherever the clamp fired, and
/// equals the unclamped reading — bit for bit — wherever it did not), so the
/// clamp is pinned at the wrong-level, wrong-branch and unconditional-clamp
/// failure modes and not merely at "some value moved."
#[test]
fn the_only_difference_from_madgraphs_own_value_is_the_positivity_clamp() {
    for name in ["oracle.json", "oracle_multigrid.json"] {
        let oracle = load_oracle_named(name);
        let clamped_member = load_member(&oracle);
        let unclamped_member = load_unclamped_member(&oracle);
        let mut clamped = 0usize;
        let mut worst_clamped = 0.0f64;
        for probe in &oracle.extrapolated {
            let want = match oracle.force_positive {
                0 => probe.xf_raw,
                1 => probe.xf_raw.max(0.0),
                2 => probe.xf_raw.max(1e-10),
                other => panic!("{name}: unhandled ForcePositive level {other}"),
            };
            assert_eq!(
                probe.xf, want,
                "{name}: xfxQ2 is not the continuation at ForcePositive \
                 {} (pdg={} x={} Q²={})",
                oracle.force_positive, probe.pdg, probe.x, probe.q2
            );

            let got_clamped: f64 = clamped_member
                .try_xfx_q2(probe.pdg, probe.x, probe.q2)
                .unwrap_or_else(|e| panic!("{name}: clamped member refused a probe: {e}"));
            let got_unclamped: f64 = unclamped_member
                .try_xfx_q2(probe.pdg, probe.x, probe.q2)
                .unwrap_or_else(|e| panic!("{name}: unclamped member refused a probe: {e}"));

            if probe.xf != probe.xf_raw {
                clamped += 1;
                worst_clamped = worst_clamped.max(probe.xf_raw.abs());
                assert_eq!(
                    got_clamped, probe.xf,
                    "{name}: this crate's clamped reading misses LHAPDF's xfxQ2 at \
                     pdg={} x={} Q²={}",
                    probe.pdg, probe.x, probe.q2
                );
            } else {
                assert_eq!(
                    got_clamped, got_unclamped,
                    "{name}: the clamp fired where LHAPDF's own did not, at \
                     pdg={} x={} Q²={}",
                    probe.pdg, probe.x, probe.q2
                );
            }
        }
        match name {
            "oracle.json" => {
                assert_eq!(
                    oracle.extrapolated.len(),
                    1190,
                    "{name}: probe count moved, re-check the expected clamp count"
                );
                assert_eq!(
                    clamped, 0,
                    "{name}: expected no clamped probes (ForcePositive 0)"
                );
            }
            "oracle_multigrid.json" => {
                assert_eq!(
                    oracle.extrapolated.len(),
                    935,
                    "{name}: probe count moved, re-check the expected clamp count"
                );
                assert_eq!(clamped, 205, "{name}: expected 205 clamped probes");
                assert!(clamped > 0, "{name}: the clamp count must not go vacuous");
            }
            other => panic!("unexpected oracle file {other}"),
        }
        println!(
            "{name}: ForcePositive {} clamps {clamped}/{} out-of-grid probes, \
             none larger than {worst_clamped:.3e} in magnitude",
            oracle.force_positive,
            oracle.extrapolated.len()
        );
    }
}

/// The resolved `ForcePositive` level, pinned against LHAPDF's own
/// `PDFInfo → PDFSet → Config` chain rather than left as a reading of a
/// config file.
///
/// Blind spot: a level that is wrong identically on both sides — a `.info`
/// and a resolved value that agree with each other but not with what
/// MadGraph's own PDF call links — is invisible here; that would need a
/// probe from MadGraph's own PDF call, which no oracle in this tree carries.
#[test]
fn the_clamp_level_is_the_one_lhapdf_resolved() {
    for name in ["oracle.json", "oracle_multigrid.json"] {
        let oracle = load_oracle_named(name);
        let set = load_set(&oracle);
        assert_eq!(
            set.info.force_positive, oracle.force_positive,
            "{name}: this crate's ForcePositive reading ({}) disagrees with \
             LHAPDF's own resolved value ({})",
            set.info.force_positive, oracle.force_positive
        );
    }
}

/// LHAPDF floors any *in-range* interpolated value below `1e-10` under
/// `ForcePositive: 2`; this crate's own clamp must reproduce every one of
/// those floors exactly.
///
/// Blind spot: the oracle carries no unclamped in-range value, so a point
/// both libraries wrongly floor — a real density that dips below `1e-10` —
/// is invisible here. Only the out-of-grid probes carry both `xf` and
/// `xf_raw`, and this test does not touch them; that comparison is
/// `the_only_difference_from_madgraphs_own_value_is_the_positivity_clamp`.
#[test]
fn an_in_grid_value_lhapdf_floors_is_floored_here_too() {
    for name in ["oracle.json", "oracle_multigrid.json"] {
        let oracle = load_oracle_named(name);
        let clamped_member = load_member(&oracle);
        let unclamped_member = load_unclamped_member(&oracle);
        let mut floored = 0usize;
        let mut smallest_margin = f64::INFINITY;
        for p in &oracle.points {
            if p.xf != 1e-10 {
                continue;
            }
            floored += 1;
            let got: f64 = clamped_member.xfx_q2(p.pdg, p.x, p.q2);
            assert_eq!(
                got, 1e-10,
                "{name}: LHAPDF floors pdg={} x={} Q²={} to 1e-10 but this crate reads \
                 {got:.17e}",
                p.pdg, p.x, p.q2
            );
            let unclamped: f64 = unclamped_member.xfx_q2(p.pdg, p.x, p.q2);
            let margin = (unclamped - 1e-10).abs() / 1e-10;
            smallest_margin = smallest_margin.min(margin);
        }
        match name {
            "oracle.json" => {
                assert_eq!(floored, 0, "{name}: expected no in-range floored points")
            }
            "oracle_multigrid.json" => {
                assert!(floored > 0, "{name}: expected some in-range floored points")
            }
            other => panic!("unexpected oracle file {other}"),
        }
        if floored > 0 {
            println!(
                "{name}: {floored} in-range points floored to 1e-10, smallest \
                 unclamped margin {smallest_margin:.3e}"
            );
        } else {
            println!("{name}: no in-range points floored to 1e-10");
        }
    }
}

/// The residual against LHAPDF, divided by the conditioning that produced it.
///
/// The flat bound above is loose because the continuation's own conditioning
/// varies by three orders across the probe set, and a bound wide enough for the
/// worst-conditioned point is wide enough to hide a real disagreement at the
/// best-conditioned one. The line `y_lo + t·(y_hi − y_lo)` has condition number
/// `(|y_lo·(1−t)| + |t·y_hi|) / |result|` with respect to a relative perturbation
/// of its two endpoints, and that is exactly the quantity to divide out: what is
/// left is the perturbation itself, which must be one ulp because both sides
/// compute the same expression from the same two numbers.
///
/// Reconstructing the endpoints from this crate's own interpolator is what makes
/// the statement checkable at all; it is sound because those endpoints are
/// independently gated against LHAPDF's (`off_knot` and `corner`, ≤4e-16 there).
///
/// Blind spot: only the `above_q2max` branch has a two-point line simple enough
/// to write a condition number for, so the other three categories are covered by
/// the flat bound alone — where they sit two orders under it.
#[test]
fn the_upper_continuation_misses_lhapdf_by_one_ulp_of_its_own_conditioning() {
    for name in ["oracle.json", "oracle_multigrid.json"] {
        let oracle = load_oracle_named(name);
        let member = load_unclamped_member(&oracle);
        let top = member.subgrids.last().expect("at least one subgrid");
        let q2_max = *top.q2.last().unwrap();
        let q2_max1 = top.q2[top.q2.len() - 2];

        let (mut worst, mut worst_at, mut worst_amp, mut n) = (0.0f64, String::new(), 1.0f64, 0);
        for probe in oracle
            .extrapolated
            .iter()
            .filter(|p| p.category == "above_q2max")
        {
            let got: f64 = member.xfx_q2(probe.pdg, probe.x, probe.q2);
            let y_lo: f64 = member.xfx_q2(probe.pdg, probe.x, q2_max);
            let y_hi: f64 = member.xfx_q2(probe.pdg, probe.x, q2_max1);
            let t = (probe.q2.ln() - q2_max.ln()) / (q2_max1.ln() - q2_max.ln());
            // Below the amplification the point carries no cancellation at all,
            // so its residual is compared at face value.
            let amp = (((y_lo * (1.0 - t)).abs() + (t * y_hi).abs())
                / got.abs().max(f64::MIN_POSITIVE))
            .max(1.0);
            let conditioned = extrap_rel_err(got, probe.xf_raw) / amp;
            n += 1;
            if conditioned >= worst {
                worst = conditioned;
                worst_amp = amp;
                worst_at = format!("pdg={} x={} Q²={}", probe.pdg, probe.x, probe.q2);
            }
        }
        println!(
            "{name}: {n} probes above the ceiling, worst conditioned residual \
             {worst:.2e} at {worst_at} (amplification {worst_amp:.2e})"
        );
        assert!(
            worst <= EXTRAP_CONDITIONED_TOL,
            "{name}: the continuation misses LHAPDF by {worst:.2e} per unit of \
             conditioning at {worst_at}, which is more than one ulp of its inputs"
        );
    }
}
