//! Validate `pdf::grid` parsing against a reference oracle generated by the
//! `parton` Python package (github.com/DavidMStraub/parton) run over the
//! pinned NNPDF23_lo_as_0130_qed set.
//!
//! Gated behind the `extended-validation` cargo feature (requires the fetched
//! PDF set + generated oracle JSON).
//!
//!     cargo test -p vibegraph-lib --features extended-validation \
//!                --test validate_pdf_grid
//!
//! Prerequisites:
//!   pixi run -e pdf-validation fetch-pdf
//!   pixi run -e pdf-validation generate-pdf-oracle
//!
//! Only the oracle's "knot" category is gated here: on a grid knot, x·f is
//! read directly out of the raw array on both the Rust and oracle side (no
//! interpolation involved), so parser correctness is the only thing under
//! test. Off-knot/seam/tail/corner points are banked in the same oracle file
//! for the interpolation session to consume.

#[cfg(feature = "extended-validation")]
mod validate_pdf_grid {
    use serde::Deserialize;
    use std::path::{Path, PathBuf};
    use vibegraph::pdf::PdfSet;

    /// Both sides parse the same ASCII float tokens independently (Rust's
    /// `f64::from_str` vs. NumPy's `loadtxt`); this tolerance absorbs any
    /// last-bit rounding difference between the two parsers without hiding a
    /// real mismatch.
    const REL_TOL: f64 = 1e-12;

    #[derive(Deserialize)]
    struct Oracle {
        set: String,
        member: u32,
        subgrids: Vec<OracleSubgrid>,
        points: Vec<OraclePoint>,
    }

    #[derive(Deserialize)]
    struct OracleSubgrid {
        nx: usize,
        nq: usize,
        flavors: Vec<i32>,
    }

    #[derive(Deserialize)]
    struct OraclePoint {
        category: String,
        pdg: i32,
        x: f64,
        q2: f64,
        xf: f64,
    }

    fn validation_dir() -> PathBuf {
        Path::new(env!("CARGO_MANIFEST_DIR")).join("../validation/pdf")
    }

    fn load_oracle() -> Oracle {
        let path = validation_dir().join("oracle.json");
        let content = std::fs::read_to_string(&path).unwrap_or_else(|e| {
            panic!(
                "failed to read {}: {e}\n\
                 run `pixi run -e pdf-validation generate-pdf-oracle` first",
                path.display()
            )
        });
        serde_json::from_str(&content)
            .unwrap_or_else(|e| panic!("failed to parse {}: {e}", path.display()))
    }

    fn load_set(oracle: &Oracle) -> PdfSet {
        let set_dir = validation_dir().join(&oracle.set);
        PdfSet::load(&set_dir, &oracle.set).unwrap_or_else(|e| {
            panic!(
                "failed to load PDF set at {}: {e}\n\
                 run `pixi run -e pdf-validation fetch-pdf` first",
                set_dir.display()
            )
        })
    }

    fn rel_close(a: f64, b: f64) -> bool {
        (a - b).abs() <= REL_TOL * a.abs().max(b.abs()).max(f64::MIN_POSITIVE)
    }

    #[test]
    fn subgrid_structure_matches_oracle() {
        let oracle = load_oracle();
        let set = load_set(&oracle);
        let member = set
            .member(oracle.member)
            .expect("failed to load reference member");

        assert_eq!(
            member.subgrids.len(),
            oracle.subgrids.len(),
            "subgrid count mismatch"
        );
        for (i, (sg, osg)) in member.subgrids.iter().zip(&oracle.subgrids).enumerate() {
            assert_eq!(sg.nx(), osg.nx, "subgrid {i}: x-knot count mismatch");
            assert_eq!(sg.nq(), osg.nq, "subgrid {i}: Q-knot count mismatch");
            assert_eq!(sg.flavors, osg.flavors, "subgrid {i}: flavor list mismatch");
        }
    }

    #[test]
    fn on_knot_values_match_oracle_exactly() {
        let oracle = load_oracle();
        let set = load_set(&oracle);
        let member = set
            .member(oracle.member)
            .expect("failed to load reference member");

        let knot_points: Vec<&OraclePoint> = oracle
            .points
            .iter()
            .filter(|p| p.category == "knot")
            .collect();
        assert!(!knot_points.is_empty(), "oracle has no on-knot points");

        let mut checked = 0usize;
        for p in &knot_points {
            let sg = member
                .subgrids
                .iter()
                .find(|sg| {
                    sg.x.iter().any(|&xv| rel_close(xv, p.x))
                        && sg.q2.iter().any(|&qv| rel_close(qv, p.q2))
                })
                .unwrap_or_else(|| panic!("no subgrid contains knot x={} q2={}", p.x, p.q2));

            let ix = sg.x.iter().position(|&xv| rel_close(xv, p.x)).unwrap();
            let iq = sg.q2.iter().position(|&qv| rel_close(qv, p.q2)).unwrap();
            let ifl = sg
                .flavor_index(p.pdg)
                .unwrap_or_else(|| panic!("flavor {} not found in subgrid", p.pdg));

            let got = sg.xf_at(ix, iq, ifl);
            assert!(
                rel_close(got, p.xf),
                "xf mismatch at pdg={} x={} q2={}: rust={got} oracle={}",
                p.pdg,
                p.x,
                p.q2,
                p.xf
            );
            checked += 1;
        }
        eprintln!("checked {checked} on-knot (pdg, x, Q²) points against the parton oracle");
    }

    #[test]
    fn info_flavors_cover_dat_flavors() {
        let oracle = load_oracle();
        let set = load_set(&oracle);
        for osg in &oracle.subgrids {
            for &f in &osg.flavors {
                assert!(
                    set.info.flavors.contains(&f),
                    "subgrid flavor {f} not listed in {}.info Flavors",
                    oracle.set
                );
            }
        }
    }
}
