//! Integration test: compare Rust HELAS amplitudes against the Fortran77
//! reference data generated by `validation/helas/gen_reference.py`.
//!
//! This test is gated behind the `extended-validation` cargo feature so it
//! does not run during normal `cargo test`.  The reference data must be
//! generated first with the `helas-validation` pixi environment.
//!
//! Full pipeline:
//!
//!     pixi run -e helas-validation validate-helas
//!
//! Or step by step:
//!
//!     pixi run -e helas-validation build-helas
//!     pixi run -e helas-validation gen-reference
//!     cargo test --features extended-validation --test helas_validation

mod common;

// SM parameters matching MadGraph's default param_card.dat:
//   aEWM1 = 132.507, Gf = 1.16639e-5, MZ = 91.188 GeV, WZ = 2.441404 GeV
const ALPHA_QED_MZ: f64 = 1.0 / 132.507;
const MDL_MZ: f64 = 91.188;
const MDL_WZ: f64 = 2.441_404;
const MDL_ME: f64 = 0.000_511;
const MDL_MMU: f64 = 0.105_658;

fn derive_gammaz_couplings() -> ([f64; 2], [f64; 2]) {
    let aew = ALPHA_QED_MZ;
    let gf = 1.166_39e-5_f64;
    let ee = (4.0 * std::f64::consts::PI * aew).sqrt();
    let sw2 = 0.5
        - (0.25 - std::f64::consts::PI * aew / (gf * std::f64::consts::SQRT_2 * MDL_MZ * MDL_MZ))
            .sqrt();
    let sw = sw2.sqrt();
    let cw = (1.0 - sw2).sqrt();
    let gc_gamma = [-ee, -ee];
    let gl_z = ee * (-0.5 + sw2) / (sw * cw);
    let gr_z = ee * sw / cw;
    ([gc_gamma[0], gc_gamma[1]], [gl_z, gr_z])
}

fn compute_m2_ee_mumu(sqrt_s: f64, cos_theta: f64) -> f64 {
    use itertools::iproduct;
    use vibegraph::helas::repr::numbers::{Charge, SpinorHelicity};
    use vibegraph::helas::{iovxxx, jioxxx};
    use vibegraph::helas::{InDiracWf, LorentzVector, OutDiracWf};
    use SpinorHelicity::{Down, Up};

    let e_beam = sqrt_s / 2.0;
    let sin_theta = (1.0 - cos_theta * cos_theta).max(0.0).sqrt();
    let (gc_gamma, gc_z) = derive_gammaz_couplings();
    let p3_e = (e_beam * e_beam - MDL_ME * MDL_ME).max(0.0).sqrt();
    let p3_mu = (e_beam * e_beam - MDL_MMU * MDL_MMU).max(0.0).sqrt();
    let p_ep = LorentzVector::new(e_beam, 0.0, 0.0, -p3_e);
    let p_em = LorentzVector::new(e_beam, 0.0, 0.0, p3_e);
    let p_mp = LorentzVector::new(e_beam, -p3_mu * sin_theta, 0.0, -p3_mu * cos_theta);
    let p_mm = LorentzVector::new(e_beam, p3_mu * sin_theta, 0.0, p3_mu * cos_theta);

    let mut sum = 0.0;
    for (nhel_em, nhel_ep) in iproduct!([Down, Up], [Down, Up]) {
        let fi_em = InDiracWf::from_momentum(p_em, MDL_ME, nhel_em, Charge::Particle);
        let fo_ep = OutDiracWf::from_momentum(p_ep, MDL_ME, nhel_ep, Charge::Antiparticle);
        let v_gamma = jioxxx(&fo_ep, &fi_em, gc_gamma, 0.0, 0.0);
        let v_z = jioxxx(&fo_ep, &fi_em, gc_z, MDL_MZ, MDL_WZ);
        for (nhel_mm, nhel_mp) in iproduct!([Down, Up], [Down, Up]) {
            let fo_mm = OutDiracWf::from_momentum(p_mm, MDL_MMU, nhel_mm, Charge::Particle);
            let fi_mp = InDiracWf::from_momentum(p_mp, MDL_MMU, nhel_mp, Charge::Antiparticle);
            let amp_gamma = iovxxx(&fo_mm, &fi_mp, &v_gamma, gc_gamma);
            let amp_z = iovxxx(&fo_mm, &fi_mp, &v_z, gc_z);
            sum += (amp_gamma + amp_z).norm_sqr();
        }
    }
    sum
}

#[cfg(test)]
mod eval_vs_hardcoded {
    use super::common::{generate_with, sm_lepton_masses_model};
    use super::{compute_m2_ee_mumu, derive_gammaz_couplings};
    use itertools::iproduct;
    use vibegraph::helas::eval::{AmplitudeEvaluator, BoundAmplitude};
    use vibegraph::helas::LorentzVector;
    use vibegraph::ufo::slha::ParamCard;

    /// Compare the runtime `AmplitudeEvaluator` against the hardcoded `compute_m2_ee_mumu`
    /// reference for e⁺e⁻→μ⁺μ⁻ at multiple angles and CM energies.
    #[test]
    fn test_eval_m2_ee_mumu_vs_hardcoded() {
        // The hardcoded reference uses physical lepton masses (MDL_ME/MDL_MMU).
        // The default SM restriction (restrict_default) locks Me/MM to zero, so a
        // param card cannot revive them; use the `lepton_masses` restriction, which
        // keeps the lepton masses settable, then supply the physical values here.
        let model = sm_lepton_masses_model();
        let sets = generate_with("e+ e- > mu+ mu-", model);
        assert!(!sets.is_empty(), "no diagram sets generated for e⁺e⁻→μ⁺μ⁻");

        // The `lepton_masses` restriction also keeps the lepton Yukawas non-zero,
        // so e⁺e⁻→μ⁺μ⁻ gains s-channel Higgs and neutral-Goldstone (G0) diagrams
        // (γ, Z, H, G0) — both scalar couplings are ∝ the lepton Yukawa. The
        // hardcoded reference is γ+Z only, so we decouple the scalars by zeroing
        // the lepton Yukawas (YUKAWA 11/13) in the param card while keeping the
        // physical masses (MASS 11/13). The H and G0 diagrams are still built but
        // evaluate to zero. TODO: once forbidden-propagator filtering (`/ H / G0`)
        // is implemented this is a good test of that syntax — drop the scalars
        // there and the Yukawa override here.
        let set = &sets[0];
        assert_eq!(set.diagrams.len(), 4, "expected 4 diagrams (γ, Z, H, G0)");

        let card = format!(
            "Block MASS\n 11 {}\n 13 {}\nBlock YUKAWA\n 11 0.0\n 13 0.0\n",
            super::MDL_ME,
            super::MDL_MMU
        )
        .parse::<ParamCard>()
        .unwrap();
        let evaluated = model.evaluate(&card);

        let evaluator =
            AmplitudeEvaluator::compile(set, model).expect("failed to compile amplitude evaluator");
        let bound = BoundAmplitude::<f64>::bind(&evaluator, &evaluated);
        assert_eq!(
            evaluator.helicities().len(),
            16,
            "expected 16 helicity combinations"
        );
        assert_eq!(evaluator.n_ext(), 4, "expected 4 external legs");
        assert_eq!(evaluator.n_in(), 2, "expected 2 incoming legs");
        assert_eq!(
            evaluator.n_diagrams(),
            set.diagrams.len(),
            "AST count mismatch"
        );

        // UFO couplings are pure imaginary; the factor of i appears twice per diagram
        // so amplitudes agree up to sign (hence MadGraph's JAMP = -AMP(γ) - AMP(Z)).
        let (gc_gamma, gc_z) = derive_gammaz_couplings();
        let gc_3 = evaluated.coupling(model.coupling_id("GC_3").unwrap());
        assert!(
            (gc_gamma[0] - gc_3.im).abs() < 1e-6,
            "photon coupling mismatch vs GC_3"
        );
        assert!(gc_3.re.abs() < 1e-6, "GC_3 has unexpected real part");
        let gc_59 = evaluated.coupling(model.coupling_id("GC_59").unwrap());
        let gc_50 = evaluated.coupling(model.coupling_id("GC_50").unwrap());
        assert!(
            (gc_z[0] - (gc_59.im + gc_50.im)).abs() < 1e-6,
            "Z left coupling mismatch"
        );
        assert!(
            (gc_z[1] - 2.0 * gc_59.im).abs() < 1e-6,
            "Z right coupling mismatch"
        );

        let me = evaluated.mass(model.particle_id("e-").unwrap());
        let mmu = evaluated.mass(model.particle_id("mu-").unwrap());

        let test_angles = (0..=100).map(|i| -1.0 + 2.0 * (i as f64) / 100.0);
        let test_roots = (1..=200).map(|i| i as f64);

        for (cos_theta, sqrt_s) in iproduct!(test_angles, test_roots) {
            let e_beam = sqrt_s / 2.0;
            let sin_theta = (1.0 - cos_theta * cos_theta).max(0.0).sqrt();
            let p3_e = (e_beam * e_beam - me * me).max(0.0).sqrt();
            let p3_mu = (e_beam * e_beam - mmu * mmu).max(0.0).sqrt();
            let momenta = vec![
                LorentzVector::new(e_beam, 0.0, 0.0, -p3_e),
                LorentzVector::new(e_beam, 0.0, 0.0, p3_e),
                LorentzVector::new(e_beam, -p3_mu * sin_theta, 0.0, -p3_mu * cos_theta),
                LorentzVector::new(e_beam, p3_mu * sin_theta, 0.0, p3_mu * cos_theta),
            ];

            let m2_runtime = bound.eval_m2(&momenta);
            let m2_hardcoded = compute_m2_ee_mumu(sqrt_s, cos_theta);

            let rel_diff = (m2_runtime - m2_hardcoded).abs() / m2_hardcoded.max(1e-10);
            assert!(
                rel_diff < 1e-4,
                "Mismatch at √s={:.1}, cos_θ={:.1}: runtime={:.4e}, hardcoded={:.4e}, rel_diff={:.2e}",
                sqrt_s, cos_theta, m2_runtime, m2_hardcoded, rel_diff
            );
        }
    }
}

#[cfg(feature = "extended-validation")]
mod extended {
    use std::path::Path;
    use vibegraph::helas::LorentzVector;

    fn compute_m2_ee_mumu_dynamic(sqrt_s: f64, cos_theta: f64) -> f64 {
        use super::common::{generate_with, sm_lepton_masses_model};
        use vibegraph::helas::eval::{AmplitudeEvaluator, BoundAmplitude};
        use vibegraph::ufo::slha::ParamCard;

        // Same situation as test_eval_m2_ee_mumu_vs_hardcoded
        let model = sm_lepton_masses_model();
        let sets = generate_with("e+ e- > mu+ mu-", model);
        let set = &sets[0];
        let card = format!(
            "Block MASS\n 11 {}\n 13 {}\nBlock YUKAWA\n 11 0.0\n 13 0.0\n",
            super::MDL_ME,
            super::MDL_MMU
        )
        .parse::<ParamCard>()
        .unwrap();
        let evaluated = model.evaluate(&card);

        let me = evaluated.mass(model.particle_id("e-").unwrap());
        let mmu = evaluated.mass(model.particle_id("mu-").unwrap());

        let evaluator =
            AmplitudeEvaluator::compile(set, model).expect("failed to compile amplitude evaluator");

        let e_beam = sqrt_s / 2.0;
        let sin_theta = (1.0 - cos_theta * cos_theta).max(0.0).sqrt();
        let p3_e = (e_beam * e_beam - me * me).max(0.0).sqrt();
        let p3_mu = (e_beam * e_beam - mmu * mmu).max(0.0).sqrt();
        let momenta = vec![
            LorentzVector::new(e_beam, 0.0, 0.0, -p3_e),
            LorentzVector::new(e_beam, 0.0, 0.0, p3_e),
            LorentzVector::new(e_beam, -p3_mu * sin_theta, 0.0, -p3_mu * cos_theta),
            LorentzVector::new(e_beam, p3_mu * sin_theta, 0.0, p3_mu * cos_theta),
        ];
        BoundAmplitude::<f64>::bind(&evaluator, &evaluated).eval_m2(&momenta)
    }

    /// Relative tolerance for comparing Rust |M|² against Fortran reference.
    /// TODO: Understand why we don't achieve machine precision as we do in validate_helas_mg
    const REL_TOL: f64 = 3e-6;

    /// Parse the CSV reference file and return rows as (sqrt_s, cos_theta, M2).
    fn read_reference_csv(path: &Path) -> Vec<(f64, f64, f64)> {
        let content = std::fs::read_to_string(path)
            .unwrap_or_else(|e| panic!("Cannot read {}: {}", path.display(), e));

        content
            .lines()
            .skip(1) // header: sqrt_s_GeV,cos_theta,M2_summed
            .filter(|l| !l.trim().is_empty())
            .map(|line| {
                let cols: Vec<&str> = line.split(',').collect();
                assert_eq!(cols.len(), 3, "Expected 3 columns in: {line}");
                let sqrt_s: f64 = cols[0].trim().parse().expect("bad sqrt_s");
                let cos_theta: f64 = cols[1].trim().parse().expect("bad cos_theta");
                let m2: f64 = cols[2].trim().parse().expect("bad M2");
                (sqrt_s, cos_theta, m2)
            })
            .collect()
    }

    #[test]
    fn helas_matches_fortran_reference() {
        let csv_path =
            Path::new(env!("CARGO_MANIFEST_DIR")).join("../validation/helas/reference.csv");

        assert!(
            csv_path.exists(),
            "Reference file not found: {}\n\
             Generate it first with:\n\
             \tpixi run -e helas-validation build-helas\n\
             \tpixi run -e helas-validation gen-reference",
            csv_path.display()
        );

        let rows = read_reference_csv(&csv_path);
        assert!(!rows.is_empty(), "reference.csv is empty");

        let mut failures = 0usize;
        for (sqrt_s, cos_theta, m2_ref) in &rows {
            let m2_rust = compute_m2_ee_mumu_dynamic(*sqrt_s, *cos_theta);
            let rel_diff = if *m2_ref != 0.0 {
                (m2_rust - m2_ref).abs() / m2_ref.abs()
            } else {
                m2_rust.abs()
            };

            if rel_diff > REL_TOL {
                eprintln!(
                    "FAIL  sqrt_s={sqrt_s:.3} cos_θ={cos_theta:.3}: \
                     Rust={m2_rust:.8e}  Fortran={m2_ref:.8e}  rel_diff={rel_diff:.2e}"
                );
                failures += 1;
            }
        }

        assert_eq!(
            failures,
            0,
            "{failures}/{} points exceeded relative tolerance {REL_TOL:.0e}",
            rows.len()
        );
    }
}
