      REAL*8 FUNCTION MATRIX1(P,NHEL,IC, IHEL)
C     
C     Generated by MadGraph5_aMC@NLO v. 3.5.7, 2024-11-29
C     By the MadGraph5_aMC@NLO Development Team
C     Visit launchpad.net/madgraph5 and amcatnlo.web.cern.ch
C     
C     Returns amplitude squared summed/avg over colors
C     for the point with external lines W(0:6,NEXTERNAL)
C     
C     Process: e+ e- > mu+ mu- ta+ ta- QCD=0 @1
C     
      IMPLICIT NONE
C     
C     CONSTANTS
C     
      INTEGER    NGRAPHS
      PARAMETER (NGRAPHS=25)
      INTEGER                 NCOMB
      PARAMETER (             NCOMB=64)
      INCLUDE 'genps.inc'
      INCLUDE 'nexternal.inc'
      INCLUDE 'maxamps.inc'
      INTEGER    NWAVEFUNCS,     NCOLOR
      PARAMETER (NWAVEFUNCS=13, NCOLOR=1)
      REAL*8     ZERO
      PARAMETER (ZERO=0D0)
      COMPLEX*16 IMAG1
      PARAMETER (IMAG1=(0D0,1D0))
      INTEGER NAMPSO, NSQAMPSO
      PARAMETER (NAMPSO=1, NSQAMPSO=1)
      LOGICAL CHOSEN_SO_CONFIGS(NSQAMPSO)
      DATA CHOSEN_SO_CONFIGS/.TRUE./
      SAVE CHOSEN_SO_CONFIGS
C     
C     ARGUMENTS 
C     
      REAL*8 P(0:3,NEXTERNAL)
      INTEGER NHEL(NEXTERNAL), IC(NEXTERNAL)
      INTEGER IHEL
C     
C     LOCAL VARIABLES 
C     
      INTEGER I,J,M,N
      COMPLEX*16 ZTEMP, TMP_JAMP(0)
      REAL*8 CF(NCOLOR,NCOLOR)
      COMPLEX*16 AMP(NGRAPHS), JAMP(NCOLOR,NAMPSO)
      COMPLEX*16 W(6,NWAVEFUNCS)
C     DBG: expose per-diagram amplitudes for vibegraph cross-check
      COMPLEX*16 AMP_DBG(NGRAPHS)
      COMMON/DBG_AMP/AMP_DBG
C     Needed for v4 models
      COMPLEX*16 DUM0,DUM1
      DATA DUM0, DUM1/(0D0, 0D0), (1D0, 0D0)/

      DOUBLE PRECISION FK_MDL_WZ
      DOUBLE PRECISION FK_MDL_WH
      DOUBLE PRECISION FK_ZERO
      SAVE FK_MDL_WZ
      SAVE FK_MDL_WH
      SAVE FK_ZERO

      LOGICAL FIRST
      DATA FIRST /.TRUE./
      SAVE FIRST
C     
C     FUNCTION
C     
      INTEGER SQSOINDEX1
C     
C     GLOBAL VARIABLES
C     
      DOUBLE PRECISION AMP2(MAXAMPS), JAMP2(0:MAXFLOW)
      COMMON/TO_AMPS/  AMP2,       JAMP2
      INCLUDE 'coupl.inc'

      DOUBLE PRECISION SMALL_WIDTH_TREATMENT
      COMMON/NARROW_WIDTH/SMALL_WIDTH_TREATMENT

      LOGICAL INIT_MODE
      COMMON/TO_DETERMINE_ZERO_HEL/INIT_MODE

      LOGICAL ZEROAMP_1(NCOMB,NGRAPHS)
      COMMON/TO_ZEROAMP_1/ZEROAMP_1

      DOUBLE PRECISION TMIN_FOR_CHANNEL
      INTEGER SDE_STRAT  ! 1 means standard single diagram enhancement strategy,
C     2 means approximation by the	denominator of the propagator
      COMMON/TO_CHANNEL_STRAT/TMIN_FOR_CHANNEL,	SDE_STRAT

C     
C     COLOR DATA
C     
      DATA (CF(I,  1),I=  1,  1) /1.000000000000000D+00/
C     1 ColorOne()
C     ----------
C     BEGIN CODE
C     ----------
      IF (FIRST) THEN
        FIRST=.FALSE.
        IF(ZERO.NE.0D0) FK_ZERO = SIGN(MAX(ABS(ZERO), ABS(ZERO
     $   *SMALL_WIDTH_TREATMENT)), ZERO)
        IF(MDL_WH.NE.0D0) FK_MDL_WH = SIGN(MAX(ABS(MDL_WH), ABS(MDL_MH
     $   *SMALL_WIDTH_TREATMENT)), MDL_WH)
        IF(ZERO.NE.0D0) FK_ZERO = SIGN(MAX(ABS(ZERO), ABS(MDL_MTA
     $   *SMALL_WIDTH_TREATMENT)), ZERO)
        IF(MDL_WZ.NE.0D0) FK_MDL_WZ = SIGN(MAX(ABS(MDL_WZ), ABS(MDL_MZ
     $   *SMALL_WIDTH_TREATMENT)), MDL_WZ)

        IF(INIT_MODE) THEN
          ZEROAMP_1(:,:) = .TRUE.
        ENDIF
      ENDIF


      CALL OXXXXX(P(0,1),ZERO,NHEL(1),-1*IC(1),W(1,1))
      CALL IXXXXX(P(0,2),ZERO,NHEL(2),+1*IC(2),W(1,2))
      CALL IXXXXX(P(0,3),ZERO,NHEL(3),-1*IC(3),W(1,3))
      CALL OXXXXX(P(0,4),ZERO,NHEL(4),+1*IC(4),W(1,4))
      CALL IXXXXX(P(0,5),MDL_MTA,NHEL(5),-1*IC(5),W(1,5))
      CALL OXXXXX(P(0,6),MDL_MTA,NHEL(6),+1*IC(6),W(1,6))
      CALL FFV1P0_3(W(1,2),W(1,1),GC_3,ZERO, FK_ZERO,W(1,7))
      CALL FFV1P0_3(W(1,3),W(1,4),GC_3,ZERO, FK_ZERO,W(1,8))
      CALL FFV1_2(W(1,5),W(1,7),GC_3,MDL_MTA, FK_ZERO,W(1,9))
C     Amplitude(s) for diagram number 1
      CALL FFV1_0(W(1,9),W(1,6),W(1,8),GC_3,AMP(1))
      CALL FFV1_1(W(1,6),W(1,7),GC_3,MDL_MTA, FK_ZERO,W(1,10))
C     Amplitude(s) for diagram number 2
      CALL FFV1_0(W(1,5),W(1,10),W(1,8),GC_3,AMP(2))
      CALL FFV2_4_3(W(1,3),W(1,4),GC_50,GC_59,MDL_MZ, FK_MDL_WZ,W(1,11)
     $ )
C     Amplitude(s) for diagram number 3
      CALL FFV2_4_0(W(1,9),W(1,6),W(1,11),GC_50,GC_59,AMP(3))
C     Amplitude(s) for diagram number 4
      CALL FFV2_4_0(W(1,5),W(1,10),W(1,11),GC_50,GC_59,AMP(4))
      CALL FFV2_4_3(W(1,2),W(1,1),GC_50,GC_59,MDL_MZ, FK_MDL_WZ,W(1,10)
     $ )
      CALL FFV2_4_2(W(1,5),W(1,10),GC_50,GC_59,MDL_MTA, FK_ZERO,W(1,9))
C     Amplitude(s) for diagram number 5
      CALL FFV1_0(W(1,9),W(1,6),W(1,8),GC_3,AMP(5))
      CALL FFV2_4_1(W(1,6),W(1,10),GC_50,GC_59,MDL_MTA, FK_ZERO,W(1,12)
     $ )
C     Amplitude(s) for diagram number 6
      CALL FFV1_0(W(1,5),W(1,12),W(1,8),GC_3,AMP(6))
C     Amplitude(s) for diagram number 7
      CALL FFV2_4_0(W(1,9),W(1,6),W(1,11),GC_50,GC_59,AMP(7))
C     Amplitude(s) for diagram number 8
      CALL FFV2_4_0(W(1,5),W(1,12),W(1,11),GC_50,GC_59,AMP(8))
      CALL FFS4_3(W(1,5),W(1,6),GC_99,MDL_MH, FK_MDL_WH,W(1,12))
C     Amplitude(s) for diagram number 9
      CALL VVS1_0(W(1,10),W(1,11),W(1,12),GC_81,AMP(9))
      CALL FFV1P0_3(W(1,5),W(1,6),GC_3,ZERO, FK_ZERO,W(1,12))
      CALL FFV1_2(W(1,3),W(1,7),GC_3,ZERO, FK_ZERO,W(1,9))
C     Amplitude(s) for diagram number 10
      CALL FFV1_0(W(1,9),W(1,4),W(1,12),GC_3,AMP(10))
      CALL FFV1_1(W(1,4),W(1,7),GC_3,ZERO, FK_ZERO,W(1,13))
C     Amplitude(s) for diagram number 11
      CALL FFV1_0(W(1,3),W(1,13),W(1,12),GC_3,AMP(11))
      CALL FFV2_4_3(W(1,5),W(1,6),GC_50,GC_59,MDL_MZ, FK_MDL_WZ,W(1,7))
C     Amplitude(s) for diagram number 12
      CALL FFV2_4_0(W(1,9),W(1,4),W(1,7),GC_50,GC_59,AMP(12))
C     Amplitude(s) for diagram number 13
      CALL FFV2_4_0(W(1,3),W(1,13),W(1,7),GC_50,GC_59,AMP(13))
      CALL FFV2_4_2(W(1,3),W(1,10),GC_50,GC_59,ZERO, FK_ZERO,W(1,13))
C     Amplitude(s) for diagram number 14
      CALL FFV1_0(W(1,13),W(1,4),W(1,12),GC_3,AMP(14))
      CALL FFV2_4_1(W(1,4),W(1,10),GC_50,GC_59,ZERO, FK_ZERO,W(1,9))
C     Amplitude(s) for diagram number 15
      CALL FFV1_0(W(1,3),W(1,9),W(1,12),GC_3,AMP(15))
C     Amplitude(s) for diagram number 16
      CALL FFV2_4_0(W(1,13),W(1,4),W(1,7),GC_50,GC_59,AMP(16))
C     Amplitude(s) for diagram number 17
      CALL FFV2_4_0(W(1,3),W(1,9),W(1,7),GC_50,GC_59,AMP(17))
      CALL FFV1_1(W(1,1),W(1,8),GC_3,ZERO, FK_ZERO,W(1,9))
C     Amplitude(s) for diagram number 18
      CALL FFV1_0(W(1,2),W(1,9),W(1,12),GC_3,AMP(18))
      CALL FFV1_1(W(1,1),W(1,12),GC_3,ZERO, FK_ZERO,W(1,3))
C     Amplitude(s) for diagram number 19
      CALL FFV1_0(W(1,2),W(1,3),W(1,8),GC_3,AMP(19))
C     Amplitude(s) for diagram number 20
      CALL FFV2_4_0(W(1,2),W(1,9),W(1,7),GC_50,GC_59,AMP(20))
      CALL FFV2_4_1(W(1,1),W(1,7),GC_50,GC_59,ZERO, FK_ZERO,W(1,9))
C     Amplitude(s) for diagram number 21
      CALL FFV1_0(W(1,2),W(1,9),W(1,8),GC_3,AMP(21))
      CALL FFV2_4_1(W(1,1),W(1,11),GC_50,GC_59,ZERO, FK_ZERO,W(1,8))
C     Amplitude(s) for diagram number 22
      CALL FFV1_0(W(1,2),W(1,8),W(1,12),GC_3,AMP(22))
C     Amplitude(s) for diagram number 23
      CALL FFV2_4_0(W(1,2),W(1,3),W(1,11),GC_50,GC_59,AMP(23))
C     Amplitude(s) for diagram number 24
      CALL FFV2_4_0(W(1,2),W(1,8),W(1,7),GC_50,GC_59,AMP(24))
C     Amplitude(s) for diagram number 25
      CALL FFV2_4_0(W(1,2),W(1,9),W(1,11),GC_50,GC_59,AMP(25))

C     DBG: copy per-diagram amplitudes for vibegraph cross-check
      DO I = 1, NGRAPHS
        AMP_DBG(I) = AMP(I)
      ENDDO

      JAMP(:,:) = (0D0,0D0)
C     JAMPs contributing to orders ALL_ORDERS=1
      JAMP(1,1) = (-1.000000000000000D+00)*AMP(1)+(-1.000000000000000D
     $ +00)*AMP(2)+(-1.000000000000000D+00)*AMP(3)+(
     $ -1.000000000000000D+00)*AMP(4)+(-1.000000000000000D+00)*AMP(5)
     $ +(-1.000000000000000D+00)*AMP(6)+(-1.000000000000000D+00)*AMP(7)
     $ +(-1.000000000000000D+00)*AMP(8)+(-1.000000000000000D+00)*AMP(9)
     $ +(-1.000000000000000D+00)*AMP(10)+(-1.000000000000000D+00)
     $ *AMP(11)+(-1.000000000000000D+00)*AMP(12)+(-1.000000000000000D
     $ +00)*AMP(13)+(-1.000000000000000D+00)*AMP(14)+(
     $ -1.000000000000000D+00)*AMP(15)+(-1.000000000000000D+00)*AMP(16)
     $ +(-1.000000000000000D+00)*AMP(17)+(-1.000000000000000D+00)
     $ *AMP(18)+(-1.000000000000000D+00)*AMP(19)+(-1.000000000000000D
     $ +00)*AMP(20)+(-1.000000000000000D+00)*AMP(21)+(
     $ -1.000000000000000D+00)*AMP(22)+(-1.000000000000000D+00)*AMP(23)
     $ +(-1.000000000000000D+00)*AMP(24)+(-1.000000000000000D+00)
     $ *AMP(25)

      IF(INIT_MODE)THEN
        DO I=1, NGRAPHS
          IF (AMP(I).NE.0) THEN
            ZEROAMP_1(IHEL,I) = .FALSE.
          ENDIF
        ENDDO
      ENDIF

      MATRIX1 = 0.D0
      DO M = 1, NAMPSO
        DO I = 1, NCOLOR
          ZTEMP = (0.D0,0.D0)
          DO J = 1, NCOLOR
            ZTEMP = ZTEMP + CF(J,I)*JAMP(J,M)
          ENDDO
          DO N = 1, NAMPSO

            MATRIX1 = MATRIX1 + ZTEMP*DCONJG(JAMP(I,N))

          ENDDO
        ENDDO
      ENDDO

      IF(SDE_STRAT.EQ.1)THEN
        AMP2(1)=AMP2(1)+AMP(1)*DCONJG(AMP(1))
        AMP2(2)=AMP2(2)+AMP(2)*DCONJG(AMP(2))
        AMP2(3)=AMP2(3)+AMP(3)*DCONJG(AMP(3))
        AMP2(4)=AMP2(4)+AMP(4)*DCONJG(AMP(4))
        AMP2(5)=AMP2(5)+AMP(5)*DCONJG(AMP(5))
        AMP2(6)=AMP2(6)+AMP(6)*DCONJG(AMP(6))
        AMP2(7)=AMP2(7)+AMP(7)*DCONJG(AMP(7))
        AMP2(8)=AMP2(8)+AMP(8)*DCONJG(AMP(8))
        AMP2(9)=AMP2(9)+AMP(9)*DCONJG(AMP(9))
        AMP2(10)=AMP2(10)+AMP(10)*DCONJG(AMP(10))
        AMP2(11)=AMP2(11)+AMP(11)*DCONJG(AMP(11))
        AMP2(12)=AMP2(12)+AMP(12)*DCONJG(AMP(12))
        AMP2(13)=AMP2(13)+AMP(13)*DCONJG(AMP(13))
        AMP2(14)=AMP2(14)+AMP(14)*DCONJG(AMP(14))
        AMP2(15)=AMP2(15)+AMP(15)*DCONJG(AMP(15))
        AMP2(16)=AMP2(16)+AMP(16)*DCONJG(AMP(16))
        AMP2(17)=AMP2(17)+AMP(17)*DCONJG(AMP(17))
        AMP2(18)=AMP2(18)+AMP(18)*DCONJG(AMP(18))
        AMP2(19)=AMP2(19)+AMP(19)*DCONJG(AMP(19))
        AMP2(20)=AMP2(20)+AMP(20)*DCONJG(AMP(20))
        AMP2(21)=AMP2(21)+AMP(21)*DCONJG(AMP(21))
        AMP2(22)=AMP2(22)+AMP(22)*DCONJG(AMP(22))
        AMP2(23)=AMP2(23)+AMP(23)*DCONJG(AMP(23))
        AMP2(24)=AMP2(24)+AMP(24)*DCONJG(AMP(24))
        AMP2(25)=AMP2(25)+AMP(25)*DCONJG(AMP(25))
      ENDIF

      DO I = 1, NCOLOR
        DO M = 1, NAMPSO
          DO N = 1, NAMPSO

            JAMP2(I)=JAMP2(I)+DABS(DBLE(JAMP(I,M)*DCONJG(JAMP(I,N))))

          ENDDO
        ENDDO
      ENDDO

      END

      SUBROUTINE PRINT_ZERO_AMP_1()

      IMPLICIT NONE
      INTEGER    NGRAPHS
      PARAMETER (NGRAPHS=25)

      INTEGER    NCOMB
      PARAMETER (NCOMB=64)

      LOGICAL ZEROAMP_1(NCOMB, NGRAPHS)
      COMMON/TO_ZEROAMP_1/ZEROAMP_1

      INTEGER I,J
      LOGICAL ALL_FALSE

      DO I=1, NGRAPHS
        ALL_FALSE = .TRUE.
        DO J=1,NCOMB
          IF (.NOT.ZEROAMP_1(J, I)) THEN
            ALL_FALSE = .FALSE.
            EXIT
          ENDIF
        ENDDO
        IF (ALL_FALSE) THEN
          WRITE(*,*) 'Amplitude/ZEROAMP:', 1, I
        ELSE
          DO J=1,NCOMB
            IF (ZEROAMP_1(J, I)) THEN
              WRITE(*,*) 'HEL/ZEROAMP:', 1, J  , I
            ENDIF
          ENDDO
        ENDIF
      ENDDO

      RETURN
      END
C     Set of functions to handle the array indices of the split orders


      INTEGER FUNCTION SQSOINDEX1(ORDERINDEXA, ORDERINDEXB)
C     
C     This functions plays the role of the interference matrix. It can
C      be hardcoded or 
C     made more elegant using hashtables if its execution speed ever
C      becomes a relevant
C     factor. From two split order indices, it return the
C      corresponding index in the squared 
C     order canonical ordering.
C     
C     CONSTANTS
C     

      INTEGER    NSO, NSQUAREDSO, NAMPSO
      PARAMETER (NSO=1, NSQUAREDSO=1, NAMPSO=1)
C     
C     ARGUMENTS
C     
      INTEGER ORDERINDEXA, ORDERINDEXB
C     
C     LOCAL VARIABLES
C     
      INTEGER I, SQORDERS(NSO)
      INTEGER AMPSPLITORDERS(NAMPSO,NSO)
      DATA (AMPSPLITORDERS(  1,I),I=  1,  1) /    1/
      COMMON/AMPSPLITORDERS1/AMPSPLITORDERS
C     
C     FUNCTION
C     
      INTEGER SOINDEX_FOR_SQUARED_ORDERS1
C     
C     BEGIN CODE
C     
      DO I=1,NSO
        SQORDERS(I)=AMPSPLITORDERS(ORDERINDEXA,I)
     $   +AMPSPLITORDERS(ORDERINDEXB,I)
      ENDDO
      SQSOINDEX1=SOINDEX_FOR_SQUARED_ORDERS1(SQORDERS)
      END

      INTEGER FUNCTION SOINDEX_FOR_SQUARED_ORDERS1(ORDERS)
C     
C     This functions returns the integer index identifying the squared
C      split orders list passed in argument which corresponds to the
C      values of the following list of couplings (and in this order).
C     []
C     
C     CONSTANTS
C     
      INTEGER    NSO, NSQSO, NAMPSO
      PARAMETER (NSO=1, NSQSO=1, NAMPSO=1)
C     
C     ARGUMENTS
C     
      INTEGER ORDERS(NSO)
C     
C     LOCAL VARIABLES
C     
      INTEGER I,J
      INTEGER SQSPLITORDERS(NSQSO,NSO)
      DATA (SQSPLITORDERS(  1,I),I=  1,  1) /    2/
      COMMON/SQPLITORDERS1/SQPLITORDERS
C     
C     BEGIN CODE
C     
      DO I=1,NSQSO
        DO J=1,NSO
          IF (ORDERS(J).NE.SQSPLITORDERS(I,J)) GOTO 1009
        ENDDO
        SOINDEX_FOR_SQUARED_ORDERS1 = I
        RETURN
 1009   CONTINUE
      ENDDO

      WRITE(*,*) 'ERROR:: Stopping in function'
      WRITE(*,*) 'SOINDEX_FOR_SQUARED_ORDERS1'
      WRITE(*,*) 'Could not find squared orders ',(ORDERS(I),I=1,NSO)
      STOP

      END

      SUBROUTINE GET_NSQSO_BORN1(NSQSO)
C     
C     Simple subroutine returning the number of squared split order
C     contributions returned when calling smatrix_split_orders 
C     

      INTEGER    NSQUAREDSO
      PARAMETER  (NSQUAREDSO=1)

      INTEGER NSQSO

      NSQSO=NSQUAREDSO

      END

C     This is the inverse subroutine of SOINDEX_FOR_SQUARED_ORDERS.
C      Not directly useful, but provided nonetheless.
      SUBROUTINE GET_SQUARED_ORDERS_FOR_SOINDEX1(SOINDEX,ORDERS)
C     
C     This functions returns the orders identified by the squared
C      split order index in argument. Order values correspond to
C      following list of couplings (and in this order):
C     []
C     
C     CONSTANTS
C     
      INTEGER    NSO, NSQSO
      PARAMETER (NSO=1, NSQSO=1)
C     
C     ARGUMENTS
C     
      INTEGER SOINDEX, ORDERS(NSO)
C     
C     LOCAL VARIABLES
C     
      INTEGER I
      INTEGER SQPLITORDERS(NSQSO,NSO)
      COMMON/SQPLITORDERS1/SQPLITORDERS
C     
C     BEGIN CODE
C     
      IF (SOINDEX.GT.0.AND.SOINDEX.LE.NSQSO) THEN
        DO I=1,NSO
          ORDERS(I) =  SQPLITORDERS(SOINDEX,I)
        ENDDO
        RETURN
      ENDIF

      WRITE(*,*) 'ERROR:: Stopping function'
     $ //' GET_SQUARED_ORDERS_FOR_SOINDEX1'
      WRITE(*,*) 'Could not find squared orders index ',SOINDEX
      STOP

      END SUBROUTINE

C     This is the inverse subroutine of getting amplitude SO orders.
C      Not directly useful, but provided nonetheless.
      SUBROUTINE GET_ORDERS_FOR_AMPSOINDEX1(SOINDEX,ORDERS)
C     
C     This functions returns the orders identified by the split order
C      index in argument. Order values correspond to following list of
C      couplings (and in this order):
C     []
C     
C     CONSTANTS
C     
      INTEGER    NSO, NAMPSO
      PARAMETER (NSO=1, NAMPSO=1)
C     
C     ARGUMENTS
C     
      INTEGER SOINDEX, ORDERS(NSO)
C     
C     LOCAL VARIABLES
C     
      INTEGER I
      INTEGER AMPSPLITORDERS(NAMPSO,NSO)
      COMMON/AMPSPLITORDERS1/AMPSPLITORDERS
C     
C     BEGIN CODE
C     
      IF (SOINDEX.GT.0.AND.SOINDEX.LE.NAMPSO) THEN
        DO I=1,NSO
          ORDERS(I) =  AMPSPLITORDERS(SOINDEX,I)
        ENDDO
        RETURN
      ENDIF

      WRITE(*,*) 'ERROR:: Stopping function GET_ORDERS_FOR_AMPSOINDEX1'
      WRITE(*,*) 'Could not find amplitude split orders index ',SOINDEX
      STOP

      END SUBROUTINE

C     This function is not directly useful, but included for
C      completeness
      INTEGER FUNCTION SOINDEX_FOR_AMPORDERS1(ORDERS)
C     
C     This functions returns the integer index identifying the
C      amplitude split orders passed in argument which correspond to
C      the values of the following list of couplings (and in this
C      order):
C     []
C     
C     CONSTANTS
C     
      INTEGER    NSO, NAMPSO
      PARAMETER (NSO=1, NAMPSO=1)
C     
C     ARGUMENTS
C     
      INTEGER ORDERS(NSO)
C     
C     LOCAL VARIABLES
C     
      INTEGER I,J
      INTEGER AMPSPLITORDERS(NAMPSO,NSO)
      COMMON/AMPSPLITORDERS1/AMPSPLITORDERS
C     
C     BEGIN CODE
C     
      DO I=1,NAMPSO
        DO J=1,NSO
          IF (ORDERS(J).NE.AMPSPLITORDERS(I,J)) GOTO 1009
        ENDDO
        SOINDEX_FOR_AMPORDERS1 = I
        RETURN
 1009   CONTINUE
      ENDDO

      WRITE(*,*) 'ERROR:: Stopping function SOINDEX_FOR_AMPORDERS1'
      WRITE(*,*) 'Could not find squared orders ',(ORDERS(I),I=1,NSO)
      STOP

      END

