#!/usr/bin/env bash
# Render the CLI reference chapter of the docs book from the binary's own help
# text: `vibegraph --help` followed by `<command> --help` for every subcommand.
#
# Usage: scripts/gen-cli-docs.sh [path-to-vibegraph-binary]
#
# Writes docs/src/cli/reference.md. The chapter is committed so the book builds
# from a bare checkout, and `vibegraph-cli/tests/cli_reference_docs.rs` fails
# whenever the committed chapter no longer matches the binary — rerun this
# script after changing a flag or its help text.
set -euo pipefail

repo="$(cd "$(dirname "$0")/.." && pwd)"
out="$repo/docs/src/cli/reference.md"

if [[ $# -ge 1 ]]; then
  bin="$1"
else
  cargo build -q -p vibegraph
  bin="$repo/target/debug/vibegraph"
fi

# `help` is clap's own subcommand and has no page of its own.
commands=(integrate generate check-events)

{
  echo '<!-- Generated by scripts/gen-cli-docs.sh from `vibegraph --help`; do not edit. -->'
  echo '# Command reference'
  echo
  echo 'The text below is what the binary prints for `--help`, for the top-level command'
  echo 'and for each subcommand. The [command-line overview](overview.md) explains how'
  echo 'the commands fit together.'
  echo
  echo '## `vibegraph`'
  echo
  echo '```text'
  "$bin" --help
  echo '```'
  for cmd in "${commands[@]}"; do
    echo
    echo "## \`vibegraph $cmd\`"
    echo
    echo '```text'
    "$bin" "$cmd" --help
    echo '```'
  done
} > "$out"

echo "wrote $out"
