#!/usr/bin/env python3
"""Evaluate the SM UFO's analytic two-body partial widths as MadGraph does.

The SM UFO ships `decays.py`: one `Decay` per unstable particle, mapping each
daughter pair to an analytic width expression — what MadGraph's
`compute_widths` evaluates for a two-body channel. This script evaluates every
entry with MadGraph's own `model_reader` on the parameters of the default
restriction (`restrict_default.dat`, the card `import model sm` restricts to),
and writes the kinematically open ones to `sm_decay_widths.json`: the hermetic
oracle the `1 -> 2` width gate compares against.

The full model is read and the restrict card set as its parameter card, rather
than the restricted model read: restriction removes every parameter it pins to
zero or one (`Me`, `CKM1x1`, ...), and the expressions still name them.

A channel is written when the parent is massive, the daughters' masses sum below
the parent's, and the expression evaluates to a real positive number (the
kinematically closed `H > W+ W-` is imaginary there, for instance).

Usage: pixi run -e madgraph python validation/madgraph/dump_sm_decay_widths.py
"""

import cmath
import importlib
import io
import json
import os
import re
import sys
from contextlib import redirect_stdout

HERE = os.path.dirname(os.path.abspath(__file__))
REPO_ROOT = os.path.dirname(os.path.dirname(HERE))
MG5_ROOT = os.path.join(REPO_ROOT, "research", "refs", "mg5amcnlo")
OUT = os.path.join(HERE, "sm_decay_widths.json")

sys.path.insert(0, MG5_ROOT)

import models as ufomodels  # noqa: E402
import models.import_ufo as import_ufo  # noqa: E402
import models.model_reader as model_reader  # noqa: E402


def main():
    card = os.path.join(MG5_ROOT, "models", "sm", "restrict_default.dat")
    with redirect_stdout(io.StringIO()):
        model = import_ufo.import_model("sm", restrict=False)
        reader = model_reader.ModelReader(model)
        reader.set_parameters_and_couplings(card)
    params = {
        (k[len("mdl_"):] if k.startswith("mdl_") else k): v
        for k, v in reader.get("parameter_dict").items()
    }
    ufo = ufomodels.load_model(import_ufo.find_ufo_path("sm"))
    decays = importlib.import_module(ufo.__name__ + ".decays")
    env = {"cmath": cmath, "complexconjugate": lambda x: complex(x).conjugate(), "abs": abs}

    def mass(particle):
        return abs(complex(params[particle.mass.name]).real) if particle.mass.name != "ZERO" else 0.0

    rows = []
    for decay in decays.all_decays:
        parent = decay.particle
        m_parent = mass(parent)
        if m_parent == 0.0:
            continue
        for daughters, expr in decay.partial_widths.items():
            if sum(mass(d) for d in daughters) >= m_parent:
                continue
            width = complex(eval(expr, env, params))
            if abs(width.imag) > 1e-12 * abs(width.real) or not width.real > 0.0:
                continue
            rows.append(
                {
                    "parent": parent.name,
                    "daughters": [d.name for d in daughters],
                    "width_gev": width.real,
                    "expression": expr,
                }
            )

    version = re.search(r"version\s*=\s*(\S+)", open(os.path.join(MG5_ROOT, "VERSION")).read()).group(1)
    out = {
        "_comment": "The SM UFO's decays.py two-body partial widths (GeV), evaluated by "
        "MadGraph's model_reader on restrict_default.dat's parameters; kinematically open "
        "channels only. Generated by validation/madgraph/dump_sm_decay_widths.py.",
        "mg_version": version,
        "param_card": os.path.relpath(card, REPO_ROOT),
        "widths": rows,
    }
    with open(OUT, "w") as fh:
        json.dump(out, fh, indent=2)
    print(f"wrote {len(rows)} partial widths to {OUT}")


if __name__ == "__main__":
    main()
