#!/usr/bin/env bash
# MadEvent cross sections for the process-line restrictions and polarized legs:
# `> A` (required s-channel), `$$ A` (forbidden s-channel) and `{0}`/`{T}` on an
# outgoing W, each beside the unrestricted process it is a subset of.
#
# Rows, all on `import model sm` (restrict_default), e+ e- at sqrt(s) = 500 GeV
# on the run card MadGraph generates for the process itself, with only the beam
# energies and the event count changed; each over SEEDS:
#
#   ee_z_only    e+ e- > z > mu+ mu-        the Z diagram alone
#   ee_mumu      e+ e- > mu+ mu-            the unrestricted process: what a
#                                           filter that removed nothing reads
#   ee_no_sz     e+ e- > e+ e- $$ z         every diagram without an s-channel Z
#   ee_ee        e+ e- > e+ e-              the unrestricted process
#   wp0_wm       e+ e- > w+{0} w-           the longitudinal W+
#   wpt_wm       e+ e- > w+{T} w-           the transverse W+
#   wp_wm        e+ e- > w+ w-              the sum the two polarizations add to
#
# One MadEvent run is one draw: the seeds are what a gate reads the spread
# from, beside the error each run quotes.
#
# Only the per-seed scalars are committed (grammar_sigma_reference.json). The
# process directories and runs stay in GRAMMAR_SIGMA_WORK (default
# validation/madgraph/work/grammar_sigma), cached as madevent_seeds.sh describes.
#
# Usage: pixi run -e madgraph generate-grammar-sigma
#        ROWS="ee_z_only ee_mumu" SEEDS="1 2" ... to run a subset; rows not run
#        keep their committed entries.
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$HERE/../.." && pwd)"
. "$HERE/madevent_seeds.sh"
OUT="${GRAMMAR_SIGMA_WORK:-$HERE/work/grammar_sigma}"
RESULT_JSON="${RESULT_JSON:-$HERE/grammar_sigma_reference.json}"
SEEDS="${SEEDS:-$(seq -s " " 20260926 20260930)}"
NB_CORE="${NB_CORE:-2}"

mkdir -p "$OUT"

BEAMS="ebeam1=250;ebeam2=250;nevents=10000"
# name|proc lines (';'-separated)|overrides of the generated card
ALL_ROWS=(
  "ee_z_only|generate e+ e- > z > mu+ mu-|$BEAMS"
  "ee_mumu|generate e+ e- > mu+ mu-|$BEAMS"
  "ee_no_sz|generate e+ e- > e+ e- \$\$ z|$BEAMS"
  "ee_ee|generate e+ e- > e+ e-|$BEAMS"
  "wp0_wm|generate e+ e- > w+{0} w-|$BEAMS"
  "wpt_wm|generate e+ e- > w+{T} w-|$BEAMS"
  "wp_wm|generate e+ e- > w+ w-|$BEAMS"
)
ROWS="${ROWS:-$(printf '%s\n' "${ALL_ROWS[@]}" | cut -d'|' -f1 | tr '\n' ' ')}"

RESULTS="$OUT/rows_$$.txt"
: > "$RESULTS"
for row in "${ALL_ROWS[@]}"; do
  IFS='|' read -r name proc overrides <<< "$row"
  case " $ROWS " in *" $name "*) ;; *) continue ;; esac
  procdir="$OUT/$name"
  mes_generate_dir "$procdir" "$proc" "$NB_CORE"
  sde="$(awk '/= *sde_strategy/{print $1}' "$procdir/Cards/run_card_default.dat")"
  for seed in $SEEDS; do
    mes_install_card "$procdir/Cards/run_card_default.dat" "$procdir/Cards/run_card.dat" "$overrides" "$seed"
    result="$(mes_run_seed "$procdir" "${name}_$seed" "$OUT/${name}_$seed.log")"
    read -r sigma err wall <<< "$result"
    printf '%s|%s|%s|%s|%s|%s|%s|%s\n' "$name" "$proc" "$overrides" "$sde" "$seed" "$sigma" "$err" "$wall" >> "$RESULTS"
    echo "    $name $seed: $sigma +- $err" >&2
  done
done

python3 - "$RESULTS" "$RESULT_JSON" "$ROOT/research/refs/mg5amcnlo/VERSION" <<'PY'
import json, os, re, sys
rows_path, out_path, version_path = sys.argv[1:4]
old = json.load(open(out_path))["rows"] if os.path.exists(out_path) else {}
rows = {}
for line in open(rows_path):
    name, proc, overrides, sde, seed, sigma, err, wall = line.rstrip("\n").split("|")
    row = rows.setdefault(name, {
        "process": proc.replace("generate ", "", 1),
        "run_card": "generated default",
        "overrides": overrides,
        "generated_sde_strategy": int(sde) if sde else None,
        "runs": [],
    })
    row["runs"].append({"iseed": int(seed), "sigma_pb": float(sigma), "err_pb": float(err),
                        "wall_s": int(wall)})
old.update(rows)
version = re.search(r"version\s*=\s*(\S+)", open(version_path).read()).group(1)
out = {
    "_comment": "MadEvent cross sections (pb) for `>`, `$$` and polarized-leg process lines "
                "and their unrestricted controls, one run per iseed, 10k unweighted events "
                "each. Generated by validation/madgraph/gen_grammar_sigma.sh.",
    "mg_version": version,
    "rows": dict(sorted(old.items())),
}
json.dump(out, open(out_path, "w"), indent=2)
print("wrote", out_path)
PY
rm -f "$RESULTS"
