#!/usr/bin/env bash
# MadEvent cross sections for the forbidden on-shell s-channel (`$ A`) gate.
#
# `$ A` keeps every diagram and rejects a phase-space point in each integration
# configuration whose marked `A` line is inside |m - M| < bwcutoff * Gamma
# (myamp.f's cut_bw, gForceBW = 2); banner.py forces sde_strategy = 1 for such
# a process. Each row below is one process under one run card, run over SEEDS
# so the gate reads MadEvent's own seed spread and not only its quoted error.
#
# Rows, all on `import model sm` (restrict_default):
#
#   ee_z_pole       e+ e- > mu+ mu- $ z     sqrt(s) = M_Z: every point is inside
#                                           the Z window
#   ee_z_100        e+ e- > mu+ mu- $ z     sqrt(s) = 100: inside at bwcutoff 15
#   ee_z_100_bw3    e+ e- > mu+ mu- $ z     sqrt(s) = 100, bwcutoff 3: outside
#   ee_z_200        e+ e- > mu+ mu- $ z     sqrt(s) = 200: outside
#   ee_pole, ee_100 e+ e- > mu+ mu-         the unrestricted process, the
#                                           comparison a veto that never fired
#                                           would match
#   uu_tt           u u~ > w+ b w- b~ $ t t~ fixed sqrt(s) = 500, both top
#                                           windows vetoed pointwise, generated by
#                                           the patched tree (below)
#   uu_tt_mg371     the same, generated by the pinned tree as it is: its top
#                                           line is never zeroed
#   uu_full         u u~ > w+ b w- b~       the unrestricted process
#   t_bev_w         t > b e+ ve $ w+        the one-incoming case: the W window
#                                           removed from the partial width
#   pp_z            p p > e+ e- $ z         dy13_default_run_card.dat
#   pp_full         p p > e+ e-             the same card
#   pp_z_chain      p p > z, z > e+ e-      the same card with cut_decays = T, so
#                                           the decay leptons see the cuts the
#                                           other two rows apply
#
# The e+ e-, u u~ and top rows start from a committed copy of MadGraph's own
# generated run card for the process (onshell_*_run_card.dat, written from the
# generated default when absent) with only the beams (and bwcutoff) changed;
# every row gets nevents and iseed. The Rust gate applies the same overrides to
# the same files.
#
# MadGraph 3.7.1's ALOHA writes the `P1D` step function of a fermion propagator
# computed from a vertex's second spinor slot (`FFV2P1D_1`) with the momentum's
# sign flip applied inside the square, so it never vanishes and that line is
# never zeroed (patches/aloha-p1d-flipped-fermion.patch says how). A row whose
# tree column reads `p1d` is generated by a copy of the pinned tree with that
# patch applied, kept in the work area as mg5amcnlo-p1d; the pinned checkout
# itself is never modified. Only `uu_tt` needs it: every other row's `$` line is
# a vector boson's or an even-slot fermion's, whose routines the patch leaves
# byte-identical. `uu_tt_mg371` keeps the unpatched reading as the defect's
# evidence.
#
# The process directories and runs stay in ONSHELL_WORK (default
# validation/madgraph/work/onshell_veto), cached as madevent_seeds.sh describes.
#
# Usage: pixi run -e madgraph generate-onshell-veto
#        (ROWS="ee_z_pole ee_z_200" and SEEDS="1 2" narrow a run; rows already in
#        the JSON are kept)
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$HERE/../.." && pwd)"
. "$HERE/madevent_seeds.sh"
OUT="${ONSHELL_WORK:-$HERE/work/onshell_veto}"
RESULT_JSON="${RESULT_JSON:-$HERE/onshell_veto_reference.json}"
SEEDS="${SEEDS:-$(seq -s " " 20260925 20260929)}"
NB_CORE="${NB_CORE:-2}"
P1D_PATCH="$HERE/patches/aloha-p1d-flipped-fermion.patch"

mkdir -p "$OUT"

# The patched copy of the pinned tree, made once. A copy that exists is reused
# only if it was made from this patch.
p1d_tree() {
  local tree="$OUT/mg5amcnlo-p1d" stamp
  stamp="$(mes_sha256 "$P1D_PATCH")"
  if [ ! -f "$tree/.vg_patch" ] || [ "$(cat "$tree/.vg_patch")" != "$stamp" ]; then
    echo ">>> copying the pinned MadGraph tree and applying $(basename "$P1D_PATCH")" >&2
    rm -rf "$tree"
    cp -a "$ROOT/research/refs/mg5amcnlo" "$tree"
    rm -rf "$tree/aloha/__pycache__"
    find "$tree/models" -name aloha.pkl -delete
    patch -p1 -s -d "$tree" < "$P1D_PATCH"
    echo "$stamp" > "$tree/.vg_patch"
  fi
  echo "$tree"
}

# name|proc lines (';'-separated)|base card|overrides|tree (pinned or p1d)
ALL_ROWS=(
  "ee_z_pole|generate e+ e- > mu+ mu- \$ z|onshell_ee_run_card.dat|ebeam1=45.594;ebeam2=45.594;nevents=10000|pinned"
  "ee_z_100|generate e+ e- > mu+ mu- \$ z|onshell_ee_run_card.dat|ebeam1=50;ebeam2=50;nevents=10000|pinned"
  "ee_z_100_bw3|generate e+ e- > mu+ mu- \$ z|onshell_ee_run_card.dat|ebeam1=50;ebeam2=50;bwcutoff=3;nevents=10000|pinned"
  "ee_z_200|generate e+ e- > mu+ mu- \$ z|onshell_ee_run_card.dat|ebeam1=100;ebeam2=100;nevents=10000|pinned"
  "ee_pole|generate e+ e- > mu+ mu-|onshell_ee_run_card.dat|ebeam1=45.594;ebeam2=45.594;nevents=10000|pinned"
  "ee_100|generate e+ e- > mu+ mu-|onshell_ee_run_card.dat|ebeam1=50;ebeam2=50;nevents=10000|pinned"
  "uu_tt|generate u u~ > w+ b w- b~ \$ t t~|onshell_uu_run_card.dat|lpp1=0;lpp2=0;ebeam1=250;ebeam2=250;nevents=10000|p1d"
  "uu_tt_mg371|generate u u~ > w+ b w- b~ \$ t t~|onshell_uu_run_card.dat|lpp1=0;lpp2=0;ebeam1=250;ebeam2=250;nevents=10000|pinned"
  "uu_full|generate u u~ > w+ b w- b~|onshell_uu_run_card.dat|lpp1=0;lpp2=0;ebeam1=250;ebeam2=250;nevents=10000|pinned"
  "t_bev_w|generate t > b e+ ve \$ w+|onshell_t_bev_run_card.dat|nevents=10000|pinned"
  "pp_z|generate p p > e+ e- \$ z|dy13_default_run_card.dat|nevents=20000|pinned"
  "pp_full|generate p p > e+ e-|dy13_default_run_card.dat|nevents=20000|pinned"
  "pp_z_chain|generate p p > z, z > e+ e-|dy13_default_run_card.dat|nevents=20000;cut_decays=True|pinned"
)
ROWS="${ROWS:-$(printf '%s\n' "${ALL_ROWS[@]}" | cut -d'|' -f1 | tr '\n' ' ')}"

RESULTS="$OUT/rows_$$.txt"
: > "$RESULTS"
for row in "${ALL_ROWS[@]}"; do
  IFS='|' read -r name proc base overrides tree <<< "$row"
  case " $ROWS " in *" $name "*) ;; *) continue ;; esac
  key="$(echo "$proc" | tr -c 'a-zA-Z0-9\n' '_' | tr -s '_')"
  if [ "$tree" = p1d ]; then
    # Named by the patch's hash, so a changed patch regenerates the directory.
    procdir="$OUT/p1d_$(mes_sha256 "$P1D_PATCH" | cut -c1-12)_$key"
    VG_MG5_ROOT="$(p1d_tree)" mes_generate_dir "$procdir" "$proc" "$NB_CORE"
    tree_label="pinned + patches/$(basename "$P1D_PATCH")"
  else
    procdir="$OUT/$key"
    mes_generate_dir "$procdir" "$proc" "$NB_CORE"
    tree_label="pinned"
  fi
  base_path="$HERE/$base"
  [ -f "$base_path" ] || cp "$procdir/Cards/run_card_default.dat" "$base_path"
  sde="$(awk '/= *sde_strategy/{print $1}' "$procdir/Cards/run_card_default.dat")"
  for seed in $SEEDS; do
    mes_install_card "$base_path" "$procdir/Cards/run_card.dat" "$overrides" "$seed"
    result="$(mes_run_seed "$procdir" "${name}_$seed" "$OUT/${name}_$seed.log")"
    read -r sigma err _ <<< "$result"
    printf '%s|%s|%s|%s|%s|%s|%s|%s|%s\n' "$name" "$proc" "$base" "$overrides" "$sde" "$seed" "$sigma" "$err" "$tree_label" >> "$RESULTS"
    echo "    $name $seed: $sigma +- $err" >&2
  done
done

python3 - "$RESULTS" "$RESULT_JSON" "$ROOT/research/refs/mg5amcnlo/VERSION" <<'PY'
import json, os, re, sys
rows_path, out_path, version_path = sys.argv[1:4]
old = json.load(open(out_path))["rows"] if os.path.exists(out_path) else {}
rows = {}
for line in open(rows_path):
    name, proc, base, overrides, sde, seed, sigma, err, tree = line.rstrip("\n").split("|")
    row = rows.setdefault(name, {
        "process": proc.replace("generate ", "", 1),
        "run_card": base,
        "overrides": overrides,
        "generated_sde_strategy": int(sde) if sde else None,
        "mg5_tree": tree,
        "runs": [],
    })
    row["runs"].append({"iseed": int(seed), "value": float(sigma), "err": float(err)})
old.update(rows)
version = re.search(r"version\s*=\s*(\S+)", open(version_path).read()).group(1)
out = {
    "_comment": "MadEvent results.dat values for the forbidden on-shell s-channel ($) gate, "
                "one run per iseed: cross sections in pb, the t > b e+ ve $ w+ row a "
                "partial width in GeV. Generated by validation/madgraph/gen_onshell_veto.sh.",
    "mg_version": version,
    "rows": dict(sorted(old.items())),
}
json.dump(out, open(out_path, "w"), indent=2)
print("wrote", out_path)
PY
rm -f "$RESULTS"
