#!/usr/bin/env python3
"""Bank MadGraph's per-flow JAMP() values as a committed reference for the Rust
colour-flow JAMP oracle (`vibegraph-lib/tests/color_jamp_oracle.rs`).

Why a dedicated reference and not `compare_amps.py`: the CF-contracted |M|² that
`validate_helas_mg` gates on sums the flows away, so it is blind to a per-flow
phase, a per-flow normalisation, or a permutation of the colour basis. Those are
exactly the errors that would skew `JAMP2(i)`, the colour-flow selection weight.
The finest linear object MadGraph exposes is `JAMP(1:NCOLOR)` per helicity, so
that is what gets banked, complex and element-wise.

`compare_amps.py`'s row matcher cannot serve as that oracle on its own: for
`g g > g g` every colour-ordered partial amplitude carries the same helicity
dependence (tree-level four-gluon is MHV, Parke-Taylor), so the
[flow x helicity] JAMP matrix is rank 1 and *every* pair of rows has overlap 1.
An overlap-based matcher is free to pair rows arbitrarily there.

Output: `jamp_reference.json`, committed. Momenta come from each process's
already-generated `output/<name>_amplitude.csv` so the reference sits on the same
phase-space points `validate_helas_mg` uses.

Usage:
  pixi run -e madgraph python validation/madgraph/gen_jamp_reference.py

Prerequisites:
  pixi run -e madgraph build-amplitude     # builds mg_amp_probe_<name>
  pixi run -e madgraph generate-amplitude  # writes <name>_amplitude.csv
"""

import importlib
import itertools
import json
import os
import re
import sys

import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__))
OUTPUT_DIR = os.path.join(HERE, "output")
sys.path.insert(0, HERE)

# Every process with NCOLOR > 1 that has a compiled `mg_amp_probe_<name>` module.
PROCESSES = ["uux_to_uux", "gg_to_ttx", "gg_to_gg"]

N_POINTS = 5


def read_csv_points(name, n_points):
    """(process_str, n_ext, [momenta]) from the amplitude CSV's first rows."""
    with open(os.path.join(OUTPUT_DIR, f"{name}_amplitude.csv")) as f:
        lines = [l for l in f if l.strip()]
    process_str = next(
        l.split(":", 1)[1].strip() for l in lines if l.startswith("# process:")
    )
    n_ext = next(int(l.split(":")[1]) for l in lines if l.startswith("# n_ext:"))
    data = [l for l in lines if not l.startswith("#")][1:]  # skip column header
    points = []
    for row in data[:n_points]:
        vals = [float(x) for x in row.split(",")]
        points.append([vals[1 + 4 * leg : 5 + 4 * leg] for leg in range(n_ext)])
    return process_str, n_ext, points


def read_flow_structures(name):
    """MadGraph's per-flow colour-structure comments, in CF/JAMP index order.

    `matrix1_orig.f` prints one `C     <coeff> <structure>` line after each
    `DATA (CF(I,k),...)` block; the k-th is flow k's colour structure.
    """
    root = os.path.join(OUTPUT_DIR, name, "SubProcesses")
    for sub in sorted(os.listdir(root)):
        path = os.path.join(root, sub, "matrix1_orig.f")
        if not os.path.exists(path):
            continue
        with open(path) as f:
            text = f.read()
        structures = re.findall(
            r"DATA \(CF\(I, *\d+\),.*?\n(?:.*?\n)*?C +\d+ (\S.*?)\n", text
        )
        if structures:
            return structures
    return None


def main():
    entries = {}
    for name in PROCESSES:
        process_str, n_ext, points = read_csv_points(name, N_POINTS)
        module = importlib.import_module(f"mg_amp_probe_{name}")
        card = os.path.join(OUTPUT_DIR, name, "Cards", "param_card.dat")
        combos = [list(c) for c in itertools.product([-1, 1], repeat=n_ext)]

        banked_points = []
        for momenta in points:
            p = np.asfortranarray(np.array(momenta, dtype=np.float64).T)
            jamps = []
            for hel in combos:
                _, jamp = module.mg_eval_amp(p, np.array(hel, dtype=np.int32), card)
                jamps.append([[float(z.real), float(z.imag)] for z in np.asarray(jamp)])
            banked_points.append({"momenta": momenta, "jamps": jamps})

        n_flows = len(banked_points[0]["jamps"][0])
        entries[name] = {
            "process": process_str,
            "n_ext": n_ext,
            "n_flows": n_flows,
            "flow_structures": read_flow_structures(name),
            "helicities": combos,
            "points": banked_points,
        }
        print(f"[{name}] {process_str}: {n_flows} flows, {len(combos)} helicity "
              f"combos, {len(banked_points)} points")

    out = os.path.join(HERE, "jamp_reference.json")
    with open(out, "w") as f:
        json.dump(
            {
                "_source": "MadGraph5_aMC@NLO JAMP(1:NCOLOR) via mg_amp_probe_<name>, "
                "generated by gen_jamp_reference.py",
                "_layout": "points[k].jamps[hel][flow] = [re, im], flow in CF/JAMP "
                "index order, hel indexing `helicities`",
                "processes": entries,
            },
            f,
            indent=1,
        )
        f.write("\n")
    print(f"wrote {out}")


if __name__ == "__main__":
    main()
