#!/usr/bin/env python3
"""Bank one committed coupling table per `mg_amplitude` row of the manifest: the
model's evaluated couplings as MadGraph's generated Fortran holds them and as
MadGraph's own Python computes them, on the row's own param card.

Read back by the hermetic gate `vibegraph-lib/tests/coupling_oracle.rs`, which
adds this crate's third evaluation of the same model and card.

Two sources per row, deliberately different objects:

  python   `models.model_reader.ModelReader.set_parameters_and_couplings` on the
           restricted model the row's `.mg5` script imported. Every coupling the
           restricted model defines, evaluated by the UFO expressions themselves
           in Python floats. This is the arbiter: it is the model's own
           statement of what its couplings are.
  fortran  the `COMMON/COUPLINGS/` block of the process's compiled matrix
           element, read out of the f2py module after `SETPARA` has parsed the
           same card. Only the couplings the generated subprocess uses are
           declared there, and their values have been through MadGraph's
           Python-to-Fortran writer, which prints each parameter at a fixed
           number of significant digits.

The two therefore disagree exactly where the writer's precision bites, which is
what makes the pair worth banking: a coupling built from a long UFO literal
loses digits on the way into `Source/couplings.f`, and the loss lands on one
named coupling here instead of spreading over per-diagram amplitudes.

Usage:
  pixi run -e madgraph generate-couplings
  python validation/madgraph/gen_couplings.py ee_to_zh_smeft   # only this row

Prerequisites:
  pixi run -e madgraph build-amplitude    # builds mg_<name> / mg_amp_probe_<name>
"""

import io
import json
import os
import re
import sys
from contextlib import redirect_stdout

import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__))
REPO_ROOT = os.path.dirname(os.path.dirname(HERE))
OUTPUT_DIR = os.path.join(HERE, "output")
TABLE_DIR = os.path.join(HERE, "couplings")
MG5_ROOT = os.path.join(REPO_ROOT, "research/refs/mg5amcnlo")

sys.path.insert(0, HERE)
# The pinned MadGraph checkout, not whatever is on PATH: the reference runs were
# generated by it, so its `model_reader` is the one that speaks for the model.
sys.path.insert(0, MG5_ROOT)

import gen_amplitude  # noqa: E402  (needs this directory on sys.path first)

import models.import_ufo as import_ufo  # noqa: E402
import models.model_reader as model_reader  # noqa: E402

SCHEMA = 1


def mg5_version() -> str:
    with open(os.path.join(MG5_ROOT, "VERSION")) as f:
        for line in f:
            if line.startswith("version"):
                return line.split("=", 1)[1].strip()
    raise AssertionError(f"no version line in {MG5_ROOT}/VERSION")


def coupling_names(proc) -> list[str]:
    """The process's `COMMON/COUPLINGS/` members, in declaration order.

    Read from the generated `Source/coupl.inc` rather than from the compiled
    module, which reports its common-block members in an order of its own and
    lowercased. The UFO's own spelling is what MadGraph writes here, and it is
    the key both other sources use.
    """
    path = os.path.join(OUTPUT_DIR, proc.name, "Source", "coupl.inc")
    with open(path) as f:
        src = f.read()
    # Fixed-form continuation: a line beginning with five spaces and a marker
    # continues the previous one.
    src = re.sub(r"\n     [^ ]", "", src)
    block = re.search(r"COMMON/COUPLINGS/([^\n]*)", src)
    assert block, f"{proc.name}: no COMMON/COUPLINGS/ in {path}"
    return [n.strip() for n in block.group(1).split(",") if n.strip()]


def fortran_couplings(proc) -> dict[str, list[float]]:
    """The process's couplings as its compiled matrix element holds them.

    `SETPARA` runs on the first call into either entry point, so one evaluation
    at the row's own first grid point is what populates the block; the |M|^2 it
    returns is thrown away.
    """
    n_ext = len(proc.pdgs_in) + len(proc.pdgs_out)
    module = gen_amplitude.summed_m2_module(proc.name, n_ext)
    card = gen_amplitude.param_card_path(proc)
    module.mg_eval_m2(first_grid_point(proc), card)
    raw = module.module if isinstance(module, gen_amplitude.ProbeM2) else module
    block = raw.couplings
    values = {}
    for name in coupling_names(proc):
        values[name] = as_complex(getattr(block, name.lower()))
    return values


def as_complex(value) -> list[float]:
    """One `COMMON/COUPLINGS/` member as `[re, im]`.

    A coupling that depends on the strong coupling is declared over
    `VECSIZE_MEMMAX`, MadEvent's vectorised-event dimension, which a generated
    directory sizes at 1 and `SETPARA` fills at its first slot.
    """
    array = np.asarray(value).ravel()
    assert array.size >= 1, "an empty coupling slot"
    z = complex(array[0])
    return [z.real, z.imag]


def first_grid_point(proc) -> np.ndarray:
    """The first phase-space point of the row's own fixed grid.

    Any on-shell point would do — nothing here reads the matrix element — but
    reusing the grid's first point keeps the call inside the kinematics the
    module was built and validated for.
    """
    n_ext = len(proc.pdgs_in) + len(proc.pdgs_out)
    masses = gen_amplitude.read_masses(gen_amplitude.param_card_path(proc))
    m_in = [masses.get(abs(pdg), 0.0) for pdg in proc.pdgs_in]
    m_out = [masses.get(abs(pdg), 0.0) for pdg in proc.pdgs_out]
    rng = np.random.default_rng(proc.seed)
    sqrt_s = proc.sqrt_s_list[0]
    beam1, beam2 = gen_amplitude.beam_momenta(sqrt_s, m_in[0], m_in[1])
    out = gen_amplitude.final_state(len(m_out), sqrt_s, m_out, rng)
    p = np.zeros((4, n_ext), dtype=np.float64, order="F")
    p[:, 0] = beam1
    p[:, 1] = beam2
    for j in range(len(m_out)):
        p[:, 2 + j] = out[j]
    return p


def model_import_path(proc) -> str:
    """The `import model` argument for the row's model, absolute.

    A row that names no model was generated against MadGraph's own `sm`, which
    the pinned checkout resolves by name. A row that names one was generated
    against the work-area copy `build.sh` stages under `output/models/`, which is
    the vendored UFO plus this repository's own restrict cards — the same pair
    the Rust side loads.
    """
    if proc.model is None:
        assert proc.restrict is None, f"{proc.name}: a restrict card without a model"
        return "sm"
    path = os.path.join(OUTPUT_DIR, "models", os.path.basename(proc.model))
    return path if proc.restrict is None else f"{path}-{proc.restrict}"


def python_couplings(proc) -> dict[str, list[float]]:
    """The restricted model's couplings, evaluated by MadGraph's own Python.

    `import_ufo` writes progress and model warnings to stdout; they are captured
    so a run's output stays one line per row.
    """
    with redirect_stdout(io.StringIO()):
        model = import_ufo.import_model(model_import_path(proc))
        reader = model_reader.ModelReader(model)
        reader.set_parameters_and_couplings(gen_amplitude.param_card_path(proc))
    return {
        name: [complex(value).real, complex(value).imag]
        for name, value in reader.get("coupling_dict").items()
    }


def table(proc) -> dict:
    card_path = gen_amplitude.param_card_path(proc)
    with open(card_path) as f:
        card_lines = f.read().splitlines()
    python = python_couplings(proc)
    fortran = fortran_couplings(proc)
    missing = sorted(set(fortran) - set(python))
    assert not missing, (
        f"{proc.name}: {missing} are declared in the generated coupl.inc but "
        f"absent from the restricted model's own coupling_dict"
    )
    return {
        "schema": SCHEMA,
        "key": proc.name,
        "process": proc.process_str,
        "model": proc.model,
        "restrict": proc.restrict,
        "madgraph_version": mg5_version(),
        "param_card_path": os.path.relpath(card_path, REPO_ROOT),
        "param_card": card_lines,
        "python": {name: python[name] for name in sorted(python)},
        "fortran": {name: fortran[name] for name in sorted(fortran)},
    }


def main() -> None:
    selected = [a for a in sys.argv[1:] if not a.startswith("-")]
    known = {p.name for p in gen_amplitude.PROCESSES}
    unknown = sorted(set(selected) - known)
    assert not unknown, f"no such registered process: {unknown}"
    procs = [p for p in gen_amplitude.PROCESSES if not selected or p.name in selected]

    os.makedirs(TABLE_DIR, exist_ok=True)
    for proc in procs:
        record = table(proc)
        path = os.path.join(TABLE_DIR, f"{proc.name}.json")
        with open(path, "w") as f:
            json.dump(record, f, indent=1, sort_keys=False)
            f.write("\n")
        print(
            f"  {proc.name}: {len(record['python'])} model couplings, "
            f"{len(record['fortran'])} in the subprocess -> {os.path.relpath(path, REPO_ROOT)}"
        )
    print(f"Wrote {len(procs)} coupling tables to {os.path.relpath(TABLE_DIR, REPO_ROOT)}")


if __name__ == "__main__":
    main()
