#!/usr/bin/env bash
# Generate the MadGraph5 reference cross sections for H7 (hadronic-sigma):
# p p > e+ e- at 13 TeV, LO, PDF = NNPDF23_lo_as_0130_qed (lhaid 247000),
# fixed mu_F = m_Z, for two run cards (default cuts; m_ll in [60,120]).
#
# The committed run-card files (dy13_*_run_card.dat) are copied verbatim into
# each MadGraph process directory's Cards/run_card.dat, so MadGraph and vibegraph
# consume the identical cut/beam/PDF settings. The banked result lands in
# hadronic_sigma_reference.json (committed).
#
# Usage: pixi run -e madgraph generate-hadronic-sigma
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
OUT="$HERE/output"
mkdir -p "$OUT"
REF_JSON="$HERE/hadronic_sigma_reference.json"

# Run one card through madevent and print "<sigma> <err>" (pb) on stdout.
run_one() {
  local name="$1" card="$2" procdir="$OUT/dy13_$1"

  if [ ! -f "$procdir/bin/generate_events" ]; then
    echo ">>> [$name] generating process p p > e+ e- ..." >&2
    local tmp_mg5
    tmp_mg5="$(mktemp -t gen_dy_XXXX).mg5"
    cat > "$tmp_mg5" <<EOF
generate p p > e+ e-
output $procdir -nojpeg
EOF
    mg5_aMC "$tmp_mg5" >&2
    rm -f "$tmp_mg5"
  fi

  echo ">>> [$name] installing shared run card $card ..." >&2
  cp "$HERE/$card" "$procdir/Cards/run_card.dat"

  echo ">>> [$name] running madevent ..." >&2
  local log="$OUT/generate_$name.log"
  # The conda activation exports its own LDFLAGS, which suppresses MadGraph's
  # make_opts `STDLIB=-lc++` (its `ifeq($(origin LDFLAGS),undefined)` guard sees
  # LDFLAGS as already-set), so the LHAPDF C++ runtime symbols (__cxa_throw,
  # __gxx_personality_v0) go unresolved when madevent links libpdf.a. Append
  # -lc++ so the gensym/madevent link finds them.
  LDFLAGS="${LDFLAGS:-} -lc++" "$procdir/bin/generate_events" -f "run_$name" >"$log" 2>&1

  # MadGraph writes the combined result to SubProcesses/results.dat: field 1 is
  # the cross section (pb), field 2 its Monte-Carlo error (pb).
  local results="$procdir/SubProcesses/results.dat"
  if [ ! -s "$results" ]; then
    echo "!!! [$name] no results.dat at $results" >&2
    tail -25 "$log" >&2
    exit 1
  fi
  local s e
  s="$(awk 'NR==1{printf "%.10g", $1}' "$results")"
  e="$(awk 'NR==1{printf "%.10g", $2}' "$results")"
  if [ -z "$s" ] || [ -z "$e" ]; then
    echo "!!! [$name] could not parse sigma/err from $results" >&2
    exit 1
  fi
  echo ">>> [$name] sigma = $s +- $e pb" >&2
  echo "$s $e"
}

read -r SD ED < <(run_one default dy13_default_run_card.dat)
read -r SM EM < <(run_one mmll_60_120 dy13_mmll_run_card.dat)

python3 - "$REF_JSON" "$SD" "$ED" "$SM" "$EM" <<'PY'
import json, sys
out, sd, ed, sm, em = sys.argv[1:6]
doc = {
    "_comment": "MadGraph5 LO reference sigma(pp->e+e-) at 13 TeV, "
                "PDF NNPDF23_lo_as_0130_qed (lhaid 247000), fixed muF=muR=91.188 GeV. "
                "Generated by validation/madgraph/gen_hadronic_sigma.sh from the "
                "committed dy13_*_run_card.dat files (shared verbatim with vibegraph).",
    "default": {
        "run_card": "dy13_default_run_card.dat",
        "sigma_pb": float(sd),
        "sigma_err_pb": float(ed),
    },
    "mmll_60_120": {
        "run_card": "dy13_mmll_run_card.dat",
        "sigma_pb": float(sm),
        "sigma_err_pb": float(em),
    },
}
with open(out, "w") as f:
    json.dump(doc, f, indent=2)
    f.write("\n")
print("banked ->", out)
print(json.dumps(doc, indent=2))
PY
