#!/usr/bin/env python
"""Write `param_card.dat` for this model, in the SLHA layout MadEvent reads.

MadEvent runs this file as a subprocess from its copy of the model directory to
obtain the card of default values it fills a run's missing entries from. Every
external parameter appears once, under its own `lhablock` at its own `lhacode`;
widths are `DECAY` lines rather than a block, as SLHA has them.
"""

from __future__ import print_function

import os

from parameters import all_parameters


def external_parameters():
    """The external parameters grouped by LHA block, each sorted by LHA code."""
    blocks = {}
    for param in all_parameters:
        if param.nature != 'external':
            continue
        blocks.setdefault(param.lhablock.upper(), []).append(param)
    for entries in blocks.values():
        entries.sort(key=lambda p: [int(c) for c in p.lhacode])
    return blocks


def card_text():
    blocks = external_parameters()
    out = ['######################################################################',
           '## PARAM_CARD GENERATED BY write_param_card.py OF THIS UFO MODEL     ##',
           '######################################################################']
    for name in sorted(blocks):
        entries = blocks[name]
        out.append('')
        out.append('###################################')
        out.append('## INFORMATION FOR %s' % name)
        out.append('###################################')
        if name == 'DECAY':
            for param in entries:
                out.append('DECAY %s %e # %s'
                           % (' '.join(str(c) for c in param.lhacode),
                              param.value, param.name))
        else:
            out.append('Block %s ' % name)
            for param in entries:
                out.append('    %s %e # %s'
                           % (' '.join(str(c) for c in param.lhacode),
                              param.value, param.name))
    out.append('')
    return '\n'.join(out)


if __name__ == '__main__':
    path = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'param_card.dat')
    with open(path, 'w') as handle:
        handle.write(card_text())
